/**
 * Universal Sector Profiles for Avenqo (Phase 1).
 *
 * Configurable multi-sector catalog covering all specified industries with
 * localized names, descriptions, recommended modules, use cases,
 * synthetic demo scenarios, and regulatory constraints.
 */

export interface DemoStep {
  stepNumber: number;
  titleFr: string;
  titleEn: string;
  descriptionFr: string;
  descriptionEn: string;
  activeModule: "retail" | "crm" | "voice" | "accounting" | "marketing" | "ocr" | "central_ai";
  inputData: string;
  simulatedOutput: string;
  visualMetric: string;
}

export interface SectorProfile {
  id: string;
  nameFr: string;
  nameEn: string;
  descriptionFr: string;
  descriptionEn: string;
  iconName: string;
  recommendedModules: ("retail" | "crm" | "voice" | "accounting" | "marketing" | "ocr")[];
  useCasesFr: string[];
  useCasesEn: string[];
  workflowTemplates: string[];
  integrationPrerequisites: string[];
  regulatoryConstraintsFr: string;
  regulatoryConstraintsEn: string;
  featureAvailability: "available" | "beta";
  demoSteps: DemoStep[];
}

export const SECTOR_PROFILES: SectorProfile[] = [
  {
    id: "retail_ecommerce",
    nameFr: "Commerce & E-commerce",
    nameEn: "Retail & E-commerce",
    descriptionFr: "Boutiques physiques, vente en ligne multi-canaux (Shopify, WooCommerce, Etsy) et distribution de détail.",
    descriptionEn: "Brick-and-mortar stores, omnichannel e-commerce (Shopify, WooCommerce, Etsy), and retail distribution.",
    iconName: "ShoppingBag",
    recommendedModules: ["retail", "marketing", "crm", "accounting"],
    useCasesFr: [
      "Analyse des ventes en temps réel et anticipation des ruptures de stock",
      "Segmentation client dynamique pour campagnes de réactivation à fort panier",
      "Réconciliation automatisée des flux de paiements (Stripe, TPV)",
    ],
    useCasesEn: [
      "Real-time sales velocity and automated stockout forecasting",
      "Dynamic customer segmentation for high-AOV repeat campaigns",
      "Automated payment gateway reconciliation (Stripe, POS)",
    ],
    workflowTemplates: ["retail_stockout_alert", "ecommerce_cart_recovery", "omnichannel_daily_report"],
    integrationPrerequisites: ["Shopify / WooCommerce API", "Passerelle de paiement"],
    regulatoryConstraintsFr: "Conformité taxes provinciales (TPS/TVQ), consentement RGPD/Loi 25 pour le marketing par courriel/SMS.",
    regulatoryConstraintsEn: "Provincial tax compliance (GST/QST), GDPR/Law 25 consent for marketing emails/SMS.",
    featureAvailability: "available",
    demoSteps: [
      {
        stepNumber: 1,
        titleFr: "Importation des ventes",
        titleEn: "Sales Data Ingestion",
        descriptionFr: "Données transactionnelles fictives synchronisées",
        descriptionEn: "Simulated POS & online store transaction ingest",
        activeModule: "retail",
        inputData: "2 840 commandes (derniers 30 jours)",
        simulatedOutput: "Ventes nettes : 184 250 $ · Marge moyenne : 41.2%",
        visualMetric: "+14.8% vs N-1",
      },
      {
        stepNumber: 2,
        titleFr: "Détection d'anomalies & tendances",
        titleEn: "Trend & Anomaly Detection",
        descriptionFr: "IA Central identifie 42 clients dormants à forte valeur",
        descriptionEn: "IA Central detects 42 high-LTV dormant accounts",
        activeModule: "central_ai",
        inputData: "Recherche segment : LTV > 1 200 $, inactifs depuis 60j",
        simulatedOutput: "Segment identifié : 42 clients (panier moyen 185 $)",
        visualMetric: "Potentiel : 7 770 $",
      },
      {
        stepNumber: 3,
        titleFr: "Génération de campagne ciblée",
        titleEn: "Targeted Campaign Generation",
        descriptionFr: "Marketing IA prépare une offre personnalisée de réactivation",
        descriptionEn: "Marketing AI drafts personalized win-back offer",
        activeModule: "marketing",
        inputData: "Paramètres : courriel courtois, offre privilège -15%",
        simulatedOutput: "Brouillon prêt pour revue humaine autorisée",
        visualMetric: "Approbation requise",
      },
      {
        stepNumber: 4,
        titleFr: "Validation & Résultat projeté",
        titleEn: "Human Approval & Projection",
        descriptionFr: "L'administrateur approuve l'action en un clic",
        descriptionEn: "Manager approves execution with one click",
        activeModule: "central_ai",
        inputData: "Validation humaine effectuée",
        simulatedOutput: "Campagne prête à diffuser via canal autorisé",
        visualMetric: "+22% réactivation estimée",
      },
    ],
  },
  {
    id: "garage_auto",
    nameFr: "Garages & Concessions Automobiles",
    nameEn: "Automotive Repair & Dealerships",
    descriptionFr: "Ateliers mécaniques, carrosseries, centres de pneus et concessionnaires automobiles.",
    descriptionEn: "Auto repair shops, body shops, tire centers, and vehicle dealerships.",
    iconName: "Wrench",
    recommendedModules: ["voice", "crm", "ocr", "accounting"],
    useCasesFr: [
      "Accueil téléphonique 24/7 et qualification de pannes ou changements de pneus",
      "Prise de rendez-vous automatique synchronisée avec les ponts élévateurs",
      "Extraction OCR immédiate des factures de pièces de rechange et bons de livraison",
    ],
    useCasesEn: [
      "24/7 voice reception qualifying breakdowns and tire season bookings",
      "Automated appointment scheduling synchronized with service bay calendars",
      "Instant OCR parsing of parts supplier invoices and delivery slips",
    ],
    workflowTemplates: ["auto_seasonal_tire_booking", "parts_invoice_ocr_entry", "mechanic_service_reminder"],
    integrationPrerequisites: ["Telnyx SIP / Numéro de téléphone", "Google Calendar (bays)"],
    regulatoryConstraintsFr: "Transparence des devis automobiles et enregistrement vocal avec avis préalable.",
    regulatoryConstraintsEn: "Automotive repair estimate transparency and call recording disclosure.",
    featureAvailability: "available",
    demoSteps: [
      {
        stepNumber: 1,
        titleFr: "Appel entrant du client",
        titleEn: "Incoming Customer Call",
        descriptionFr: "Un client appelle pour un changement de pneus et freins",
        descriptionEn: "Customer calls requesting seasonal tire change and brakes",
        activeModule: "voice",
        inputData: "Appel vocal audio capté par Telnyx",
        simulatedOutput: "Qualification : Toyota RAV4 2022, freins avant + 4 pneus",
        visualMetric: "Appel qualifié",
      },
      {
        stepNumber: 2,
        titleFr: "Vérification des disponibilités",
        titleEn: "Bay Availability Check",
        descriptionFr: "Voice IA interroge CRM IA pour les créneaux atelier",
        descriptionEn: "Voice AI queries CRM AI for open mechanical bay slots",
        activeModule: "crm",
        inputData: "Recherche disponibilité : Jeudi prochain à 14h00",
        simulatedOutput: "Créneau disponible : Pont 2 libre à 14h00 (durée 90 min)",
        visualMetric: "Zéro surbooking",
      },
      {
        stepNumber: 3,
        titleFr: "Confirmation orale sécurisée",
        titleEn: "Verbal Confirmation & Guardrail",
        descriptionFr: "L'agent vocal confirme la date et le tarif estimatif avec l'appelant",
        descriptionEn: "Voice agent verbally verifies date and estimate with caller",
        activeModule: "voice",
        inputData: "Consentement explicite du client reçu",
        simulatedOutput: "SMS de confirmation envoyé avec lien d'accès",
        visualMetric: "Réservation confirmée",
      },
      {
        stepNumber: 4,
        titleFr: "Synchronisation agenda & fiche client",
        titleEn: "Calendar & Customer Sync",
        descriptionFr: "Inscription dans l'agenda de l'atelier et création du bon de travail",
        descriptionEn: "Work order logged into garage CRM and Google Calendar",
        activeModule: "central_ai",
        inputData: "Enregistrement en base de données",
        simulatedOutput: "Fiche client mise à jour · Google Calendar synchronisé",
        visualMetric: "Rendez-vous actif",
      },
    ],
  },
  {
    id: "health_clinic",
    nameFr: "Cliniques & Professionnels de la Santé",
    nameEn: "Healthcare & Medical Clinics",
    descriptionFr: "Cliniques médicales privées, dentistes, physiothérapie, psychologie et soins spécialisés.",
    descriptionEn: "Private medical practices, dental clinics, physical therapy, and specialized care.",
    iconName: "HeartPulse",
    recommendedModules: ["crm", "voice", "ocr"],
    useCasesFr: [
      "Prise de rendez-vous téléphonique intelligente avec filtrage des urgences",
      "Rappels automatiques de consultations et réduction des rendez-vous manqués",
      "Numérisation OCR de prescriptions et formulaires de consentement",
    ],
    useCasesEn: [
      "Intelligent phone appointment booking with triage and emergency redirection",
      "Automated patient appointment reminders reducing no-shows",
      "OCR digitization of consent forms, receipts, and clinical notes",
    ],
    workflowTemplates: ["clinic_patient_booking", "no_show_prevention", "prescription_ocr"],
    integrationPrerequisites: ["Google Calendar praticien", "Ligne téléphonique Telnyx"],
    regulatoryConstraintsFr: "Loi 25 (Québec) / HIPAA : données médicales protégées, chiffrement strict et consentement explicite requis.",
    regulatoryConstraintsEn: "Law 25 (Quebec) / HIPAA compliance: protected health info, strict encryption, explicit consent.",
    featureAvailability: "available",
    demoSteps: [
      {
        stepNumber: 1,
        titleFr: "Demande de consultation",
        titleEn: "Consultation Request",
        descriptionFr: "Patient sollicite une consultation de physiothérapie",
        descriptionEn: "Patient requests physical therapy evaluation",
        activeModule: "voice",
        inputData: "Demande vocale : première évaluation cervicale",
        simulatedOutput: "Qualification administrative sans collecte de diagnostic confidentiel",
        visualMetric: "Filtrage sécurisé",
      },
      {
        stepNumber: 2,
        titleFr: "Vérification des disponibilités praticien",
        titleEn: "Practitioner Availability",
        descriptionFr: "CRM IA vérifie l'agenda du spécialiste disponible",
        descriptionEn: "CRM AI checks therapist calendar availability",
        activeModule: "crm",
        inputData: "Recherche créneau : Vendredi 10h30",
        simulatedOutput: "Créneau confirmé disponible chez Dr. Tremblay",
        visualMetric: "Créneau libre",
      },
      {
        stepNumber: 3,
        titleFr: "Avis de gestion des données & consentement",
        titleEn: "Privacy & Data Consent Notice",
        descriptionFr: "Notification préalable sur la gestion confidentielle des données",
        descriptionEn: "Automated consent notice provided before appointment storage",
        activeModule: "central_ai",
        inputData: "Validation des conditions de confidentialité",
        simulatedOutput: "Données cloisonnées au locataire · Chiffrement AES-256",
        visualMetric: "Pratiques Loi 25 actives",
      },
      {
        stepNumber: 4,
        titleFr: "Confirmation & Instructions d'arrivée",
        titleEn: "Confirmation & Pre-visit Guide",
        descriptionFr: "Envoi d'instructions d'accueil et ajout à l'agenda sécurisé",
        descriptionEn: "Intake instructions issued and slot reserved on secure calendar",
        activeModule: "crm",
        inputData: "Génération du rappel patient",
        simulatedOutput: "Réservation confirmée avec rappel 24h avant",
        visualMetric: "Rendez-vous planifié",
      },
    ],
  },
  {
    id: "restaurant_cafe",
    nameFr: "Restaurants, Bars & Cafés",
    nameEn: "Restaurants, Bars & Cafes",
    descriptionFr: "Établissements de restauration, traiteurs, microbrasseries et services de livraison.",
    descriptionEn: "Dining establishments, caterers, microbreweries, and food delivery businesses.",
    iconName: "Utensils",
    recommendedModules: ["voice", "crm", "retail", "accounting"],
    useCasesFr: [
      "Prise de réservations téléphoniques pendant les heures de coupure ou rush de service",
      "Analyse des coûts matières et prévision d'affluence selon la météo et le calendrier",
      "Extraction OCR immédiate des factures fournisseurs de denrées et boissons",
    ],
    useCasesEn: [
      "Voice reservation booking during peak prep hours and rush services",
      "Ingredient cost analytics and footfall prediction based on weather/season",
      "Instant OCR extraction of food and beverage supplier delivery bills",
    ],
    workflowTemplates: ["table_reservation_voice", "food_cost_ocr_import", "shift_affluence_forecast"],
    integrationPrerequisites: ["Système POS / TPV", "Google Calendar (plans de table)"],
    regulatoryConstraintsFr: "Mentions obligatoires sur les allergènes et conformité Module d'enregistrement des ventes (MEV).",
    regulatoryConstraintsEn: "Allergen advisory requirements and restaurant sales recording module (SRM) rules.",
    featureAvailability: "available",
    demoSteps: [
      {
        stepNumber: 1,
        titleFr: "Réservation téléphonique automatique",
        titleEn: "Automated Table Booking",
        descriptionFr: "Client appelle pour réserver une table de 4 personnes ce samedi",
        descriptionEn: "Customer calls to reserve a table of 4 for Saturday night",
        activeModule: "voice",
        inputData: "Appel vocal : samedi 19h30, 4 personnes, terrasse souhaitée",
        simulatedOutput: "Disponibilité vérifiée dans le CRM de réservations",
        visualMetric: "Table libre",
      },
      {
        stepNumber: 2,
        titleFr: "Confirmation & Notes spécifiques",
        titleEn: "Dietary Notes & Confirmation",
        descriptionFr: "Prise en compte des remarques (ex: chaise haute requise)",
        descriptionEn: "Notes recorded for high chair and window seating",
        activeModule: "crm",
        inputData: "Enregistrement : Table 14 réservée",
        simulatedOutput: "SMS de rappel envoyé au client avec lien de modification",
        visualMetric: "Réservation validée",
      },
      {
        stepNumber: 3,
        titleFr: "Extraction OCR facture fournisseur",
        titleEn: "Supplier Invoice OCR",
        descriptionFr: "Le chef photographie un bordereau de livraison de produits frais",
        descriptionEn: "Chef captures delivery receipt from local seafood supplier",
        activeModule: "ocr",
        inputData: "Scan PDF/Photo : 480.50 $ (poissons & légumes)",
        simulatedOutput: "Extraction ventilée : sous-total, taxes TPS/TVQ, fournisseur",
        visualMetric: "Extraction 99.4%",
      },
      {
        stepNumber: 4,
        titleFr: "Intégration comptable préparatoire",
        titleEn: "Accounting Ledger Prep",
        descriptionFr: "Rapprochement avec le compte bancaire du restaurant",
        descriptionEn: "Expense ready for month-end close with restaurant ledger",
        activeModule: "accounting",
        inputData: "Écriture préparatoire générée",
        simulatedOutput: "Trésorerie mise à jour · Aucune double saisie manuelle",
        visualMetric: "Écriture prête",
      },
    ],
  },
  {
    id: "hair_beauty",
    nameFr: "Salons de Coiffure & Esthétique",
    nameEn: "Hair Salons & Aesthetics",
    descriptionFr: "Salons de coiffure, instituts de beauté, barbiers, spas et centres de bien-être.",
    descriptionEn: "Hair salons, beauty institutes, barbershops, day spas, and wellness centers.",
    iconName: "Sparkles",
    recommendedModules: ["voice", "crm", "marketing"],
    useCasesFr: [
      "Réception d'appels et réservation de soins pendant que les coiffeurs sont occupés",
      "Fiches clientes détaillées avec historique des prestations et formules de coloration",
      "Campagnes automatiques de rappel après 6 à 8 semaines d'intervalle",
    ],
    useCasesEn: [
      "Phone booking answering client calls while stylists are with clients",
      "Detailed client history cards storing color formulas and service notes",
      "Automated repeat reminders sent 6 to 8 weeks after last appointment",
    ],
    workflowTemplates: ["salon_appointment_voice", "client_formula_history", "recall_campaign_8weeks"],
    integrationPrerequisites: ["Telnyx Voice", "Google Calendar (agenda par fauteuil)"],
    regulatoryConstraintsFr: "Consentement pour les relances promotionnelles par SMS.",
    regulatoryConstraintsEn: "Explicit consent required for promotional SMS recalls.",
    featureAvailability: "available",
    demoSteps: [
      {
        stepNumber: 1,
        titleFr: "Appel entrant pour coupe & coloration",
        titleEn: "Voice Booking Request",
        descriptionFr: "Une cliente appelle pour un forfait balayage avec sa styliste favorite",
        descriptionEn: "Client calls for color and cut with her favorite stylist",
        activeModule: "voice",
        inputData: "Appel entrant : balayage avec Sophie, samedi matin",
        simulatedOutput: "Vérification des disponibilités de Sophie (créneau 120 min)",
        visualMetric: "Créneau trouvé",
      },
      {
        stepNumber: 2,
        titleFr: "Réservation & Enregistrement CRM",
        titleEn: "CRM Booking Entry",
        descriptionFr: "Le rendez-vous est bloqué dans le calendrier du fauteuil",
        descriptionEn: "Slot locked on stylist chair schedule and client history loaded",
        activeModule: "crm",
        inputData: "Validation créneau : Samedi à 09h30",
        simulatedOutput: "Fiche client associée avec historique de ses teintes",
        visualMetric: "Agenda à jour",
      },
      {
        stepNumber: 3,
        titleFr: "Campagne de fidélité automatique",
        titleEn: "Automated Loyalty Follow-up",
        descriptionFr: "Marketing IA programme le rappel personnalisé pour dans 7 semaines",
        descriptionEn: "Marketing AI schedules gentle maintenance reminder for 7 weeks out",
        activeModule: "marketing",
        inputData: "Règle de rétention : délai moyen entre visites = 50 jours",
        simulatedOutput: "Message pré-rédigé pour approbation",
        visualMetric: "Rétention +28%",
      },
      {
        stepNumber: 4,
        titleFr: "Confirmation client par SMS",
        titleEn: "SMS Appointment Confirmation",
        descriptionFr: "Notification de confirmation envoyée immédiatement à la cliente",
        descriptionEn: "Confirmation details delivered instantly to client",
        activeModule: "voice",
        inputData: "Notification envoyée avec rappel d'annulation 24h",
        simulatedOutput: "Confirmation instantanée · Zéro interruption en salon",
        visualMetric: "Réservé",
      },
    ],
  },
  {
    id: "real_estate",
    nameFr: "Immobilier & Gestion Locative",
    nameEn: "Real Estate & Property Management",
    descriptionFr: "Agences immobilières, courtiers, gestionnaires d'immeubles et promoteurs.",
    descriptionEn: "Real estate agencies, brokers, property managers, and developers.",
    iconName: "Building",
    recommendedModules: ["crm", "voice", "ocr", "marketing"],
    useCasesFr: [
      "Qualification immédiate des appels d'acheteurs et locataires sur les annonces",
      "Planification automatique des visites d'immeubles sans allers-retours téléphoniques",
      "Extraction OCR des baux, contrats de vente et états des lieux",
    ],
    useCasesEn: [
      "Instant qualification of buyer and renter inbound calls on listings",
      "Automated property tour booking without phone tag",
      "OCR parsing of lease agreements, sales contracts, and inspection sheets",
    ],
    workflowTemplates: ["listing_lead_qualification", "tour_booking_calendar", "lease_contract_ocr"],
    integrationPrerequisites: ["Google Calendar courtier", "Ligne d'annonce Telnyx"],
    regulatoryConstraintsFr: "Conformité OACIQ (Québec) / Real Estate Council, protection des données des locataires.",
    regulatoryConstraintsEn: "Real estate board regulatory compliance and tenant privacy guidelines.",
    featureAvailability: "available",
    demoSteps: [
      {
        stepNumber: 1,
        titleFr: "Appel sur annonce immobilière",
        titleEn: "Inbound Property Inquiry",
        descriptionFr: "Un acheteur appelle pour obtenir des informations sur un condo en vente",
        descriptionEn: "Buyer calls inquiring about a listed downtown condo",
        activeModule: "voice",
        inputData: "Appel : Condo rue Sherbrooke, budget 450 000 $, visite souhaitée",
        simulatedOutput: "Qualification : acheteur pré-qualifié hypothécaire",
        visualMetric: "Prospect qualifié",
      },
      {
        stepNumber: 2,
        titleFr: "Organisation de la visite privée",
        titleEn: "Private Showing Scheduling",
        descriptionFr: "L'agent vocal propose les plages de visite libres du courtier",
        descriptionEn: "Voice agent offers open showing windows on broker calendar",
        activeModule: "crm",
        inputData: "Vérification créneau : Dimanche à 14h00",
        simulatedOutput: "Plage de visite 45 min réservée pour le condo #402",
        visualMetric: "Visite planifiée",
      },
      {
        stepNumber: 3,
        titleFr: "Extraction OCR de promesse d'achat",
        titleEn: "Purchase Offer OCR Parsing",
        descriptionFr: "Le courtier numérise une promesse d'achat reçue",
        descriptionEn: "Broker uploads incoming purchase agreement PDF",
        activeModule: "ocr",
        inputData: "Document PDF : Contrat de 12 pages",
        simulatedOutput: "Extraction : prix offert, conditions d'inspection, date d'acte",
        visualMetric: "Données extraites",
      },
      {
        stepNumber: 4,
        titleFr: "Mise à jour du pipeline CRM",
        titleEn: "Deal Pipeline Update",
        descriptionFr: "Le dossier de transaction passe à l'étape 'Offre en cours'",
        descriptionEn: "Deal card moves to 'Pending Conditions' stage in CRM",
        activeModule: "crm",
        inputData: "Synchronisation du tableau de bord",
        simulatedOutput: "Courtier notifié avec échéancier d'inspection",
        visualMetric: "Dossier à jour",
      },
    ],
  },
  {
    id: "construction",
    nameFr: "Construction & Rénovation",
    nameEn: "Construction & Contracting",
    descriptionFr: "Entrepreneurs généraux, électriciens, plombiers, menuisiers et professionnels du bâtiment.",
    descriptionEn: "General contractors, electricians, plumbers, carpenters, and trades businesses.",
    iconName: "Hammer",
    recommendedModules: ["voice", "crm", "ocr", "accounting"],
    useCasesFr: [
      "Ne manquez aucun appel client pendant que vous êtes sur un chantier avec du bruit",
      "Qualification des demandes de devis et planification des visites d'estimation",
      "Extraction OCR immédiate des factures de quincaillerie et matériaux",
    ],
    useCasesEn: [
      "Never miss a client call while working on noisy job sites",
      "Estimates request qualification and site assessment booking",
      "Instant OCR parsing of hardware and building materials receipts",
    ],
    workflowTemplates: ["jobsite_call_capture", "estimate_visit_booking", "materials_invoice_ocr"],
    integrationPrerequisites: ["Numéro de téléphone d'entreprise Telnyx", "Google Calendar"],
    regulatoryConstraintsFr: "Licences RBQ / CCQ (Québec) et obligations légales sur les soumissions écrites.",
    regulatoryConstraintsEn: "Trade licensing requirements and written estimate compliance.",
    featureAvailability: "available",
    demoSteps: [
      {
        stepNumber: 1,
        titleFr: "Appel client pendant un chantier",
        titleEn: "Jobsite Call Capture",
        descriptionFr: "Un client appelle pour une rénovation complète de salle de bain",
        descriptionEn: "Client calls requesting full bathroom renovation quote",
        activeModule: "voice",
        inputData: "Appel téléphonique : rénovation résidentielle, début souhaité le mois prochain",
        simulatedOutput: "Voice IA qualifie l'adresse, l'ampleur et l'échéance",
        visualMetric: "Demande qualifiée",
      },
      {
        stepNumber: 2,
        titleFr: "Prise de RDV pour estimation",
        titleEn: "Site Assessment Scheduling",
        descriptionFr: "L'agent vocal planifie la visite d'estimation sur le calendrier",
        descriptionEn: "Voice agent books on-site estimate visit on contractor calendar",
        activeModule: "crm",
        inputData: "Créneau proposé : Mercredi prochain à 17h00",
        simulatedOutput: "Visite enregistrée avec adresse du chantier",
        visualMetric: "Visite fixée",
      },
      {
        stepNumber: 3,
        titleFr: "Traitement OCR des factures matériaux",
        titleEn: "Materials Receipt OCR",
        descriptionFr: "L'entrepreneur photographie un reçu de matériaux au comptoir",
        descriptionEn: "Contractor snaps lumber and plumbing supply receipt",
        activeModule: "ocr",
        inputData: "Photo de facture : 1 450.80 $ chez le fournisseur",
        simulatedOutput: "Extraction instantanée : ventilation par poste de coût",
        visualMetric: "OCR complété",
      },
      {
        stepNumber: 4,
        titleFr: "Suivi de rentabilité du chantier",
        titleEn: "Job Costing Sync",
        descriptionFr: "Affectation des dépenses au dossier client dans Avenqo",
        descriptionEn: "Costs attributed to client project file in Avenqo workspace",
        activeModule: "accounting",
        inputData: "Calcul de la marge réelle du projet",
        simulatedOutput: "Dépenses imputées · Synthèse prête pour la facturation",
        visualMetric: "Marge suivie",
      },
    ],
  },
  {
    id: "transport_logistics",
    nameFr: "Transport & Logistique",
    nameEn: "Transportation & Logistics",
    descriptionFr: "Flottes de livraison, transporteurs de fret, transitaires et entrepôts de distribution.",
    descriptionEn: "Delivery fleets, freight carriers, freight forwarders, and distribution warehouses.",
    iconName: "Truck",
    recommendedModules: ["crm", "voice", "ocr", "retail"],
    useCasesFr: [
      "Gestion des statuts de livraison et demandes de repérage par téléphone",
      "Extraction OCR automatique des bordereaux de livraison et connaissements (BOL)",
      "Suivi de la relation client avec les expéditeurs et chargeurs réguliers",
    ],
    useCasesEn: [
      "Automated phone tracking inquiries and delivery status updates",
      "Automated OCR extraction of bills of lading (BOL) and delivery manifests",
      "Carrier CRM managing regular shippers and contract accounts",
    ],
    workflowTemplates: ["delivery_status_voice_ivr", "bill_of_lading_ocr", "shipper_account_crm"],
    integrationPrerequisites: ["Système TMS ou tableurs d'expéditions", "Ligne Telnyx"],
    regulatoryConstraintsFr: "Conformité réglementaire des transports et traçabilité des manifestes de marchandises.",
    regulatoryConstraintsEn: "Freight tracking regulatory compliance and transport manifest records.",
    featureAvailability: "available",
    demoSteps: [
      {
        stepNumber: 1,
        titleFr: "Appel de suivi d'expédition",
        titleEn: "Shipment Tracking Voice Inquiry",
        descriptionFr: "Un client appelle pour connaître l'heure de livraison de son fret",
        descriptionEn: "Shipper calls asking for estimated delivery window on cargo",
        activeModule: "voice",
        inputData: "Appel vocal : numéro d'expédition #TR-8842",
        simulatedOutput: "Vérification du statut d'expédition en temps réel",
        visualMetric: "Statut repéré",
      },
      {
        stepNumber: 2,
        titleFr: "Réponse vocale instantanée",
        titleEn: "Instant Automated Response",
        descriptionFr: "L'agent vocal communique l'heure estimée et le nom du chauffeur",
        descriptionEn: "Voice agent announces delivery window and assigned truck",
        activeModule: "voice",
        inputData: "Réponse : Arrivée estimée aujourd'hui entre 14h30 et 15h15",
        simulatedOutput: "Appel résolu sans mobiliser l'équipe d'exploitation",
        visualMetric: "Appel traité",
      },
      {
        stepNumber: 3,
        titleFr: "Numérisation OCR du connaissement",
        titleEn: "Bill of Lading OCR Ingestion",
        descriptionFr: "Le chauffeur dépose la photo du bon de livraison signé",
        descriptionEn: "Driver uploads mobile scan of signed delivery slip",
        activeModule: "ocr",
        inputData: "Document numérisé : preuve de livraison signée",
        simulatedOutput: "Extraction : poids, palettes, signature, date et heure",
        visualMetric: "BOL validé",
      },
      {
        stepNumber: 4,
        titleFr: "Clôture de la commande",
        titleEn: "Order Delivery Clearance",
        descriptionFr: "Le dossier est marqué livré et la facture est prête pour émission",
        descriptionEn: "Delivery confirmed and invoice prepped for shipper account",
        activeModule: "crm",
        inputData: "Statut passé à 'Livré et vérifié'",
        simulatedOutput: "Avis envoyé au chargeur · Données archivées",
        visualMetric: "Dossier clos",
      },
    ],
  },
  {
    id: "education",
    nameFr: "Éducation & Formation",
    nameEn: "Education & Training Centers",
    descriptionFr: "Écoles de langues, centres de formation professionnelle, académies privées et cours spécialisés.",
    descriptionEn: "Language schools, vocational training centers, private academies, and tutoring institutes.",
    iconName: "GraduationCap",
    recommendedModules: ["crm", "voice", "marketing", "ocr"],
    useCasesFr: [
      "Qualification et orientation des inscriptions étudiantes par téléphone",
      "Gestion du pipeline d'admissions et suivi des prospects jusqu'à l'inscription",
      "Campagnes marketing ciblées pour les sessions et rentrées de cours",
    ],
    useCasesEn: [
      "Inbound phone qualification and guidance for student enrollment",
      "Admissions pipeline management and applicant follow-ups",
      "Targeted marketing campaigns for upcoming course intakes",
    ],
    workflowTemplates: ["admissions_inbound_voice", "course_enrollment_pipeline", "session_start_campaign"],
    integrationPrerequisites: ["Google Calendar (séances d'information)", "Ligne d'accueil Telnyx"],
    regulatoryConstraintsFr: "Protection des données personnelles des étudiants et politiques de désinscription respectées.",
    regulatoryConstraintsEn: "Student privacy protections and opt-out policies for academic communications.",
    featureAvailability: "available",
    demoSteps: [
      {
        stepNumber: 1,
        titleFr: "Demande d'information de formation",
        titleEn: "Training Inquiry Call",
        descriptionFr: "Un candidat appelle pour se renseigner sur le programme certifiant",
        descriptionEn: "Prospective student calls asking about certification program",
        activeModule: "voice",
        inputData: "Appel : Début de session, prérequis, options de financement",
        simulatedOutput: "Qualification de l'admissibilité par l'agent d'accueil",
        visualMetric: "Candidat qualifié",
      },
      {
        stepNumber: 2,
        titleFr: "Planification de l'entretien d'admission",
        titleEn: "Admissions Interview Booking",
        descriptionFr: "L'agent planifie une séance d'évaluation avec un conseiller",
        descriptionEn: "Agent reserves an interview slot with academic advisor",
        activeModule: "crm",
        inputData: "Sélection créneau : Lundi à 11h00 en visioconférence",
        simulatedOutput: "Ajout à l'agenda de l'équipe des admissions",
        visualMetric: "Entretien fixé",
      },
      {
        stepNumber: 3,
        titleFr: "Envoi automatique de la brochure",
        titleEn: "Brochure & Syllabus Dispatch",
        descriptionFr: "IA Central déclenche l'envoi du plan de cours complet par courriel",
        descriptionEn: "IA Central triggers automated course syllabus and tuition guide",
        activeModule: "central_ai",
        inputData: "Envoi courriel avec syllabus et fiche d'inscription",
        simulatedOutput: "Document acheminé avec suivi d'ouverture",
        visualMetric: "Courriel envoyé",
      },
      {
        stepNumber: 4,
        titleFr: "Suivi dans le CRM des admissions",
        titleEn: "Admissions CRM Tracking",
        descriptionFr: "La fiche prospect est mise à jour avec l'ensemble des notes",
        descriptionEn: "Prospect file logged with complete call notes and milestones",
        activeModule: "crm",
        inputData: "Statut du prospect : 'Entretien planifié'",
        simulatedOutput: "Conseiller académique assigné avec contexte d'appel",
        visualMetric: "Dossier actif",
      },
    ],
  },
  {
    id: "hospitality_tourism",
    nameFr: "Hôtellerie & Tourisme",
    nameEn: "Hospitality & Tourism",
    descriptionFr: "Hôtels indépendants, auberges, chalets de villégiature et agences d'excursions.",
    descriptionEn: "Boutique hotels, lodges, vacation rentals, and tour operators.",
    iconName: "Compass",
    recommendedModules: ["voice", "crm", "marketing", "accounting"],
    useCasesFr: [
      "Accueil téléphonique multilingue 24/7 pour renseignements et réservations de séjours",
      "Fiches clients avec préférences de séjour pour un accueil personnalisé",
      "Communication automatisée avant l'arrivée avec instructions d'accès",
    ],
    useCasesEn: [
      "24/7 multilingual phone reception for stay inquiries and bookings",
      "Guest profile management capturing room preferences and VIP status",
      "Automated pre-arrival communications with check-in access instructions",
    ],
    workflowTemplates: ["hotel_guest_inbound_voice", "guest_pre_arrival_flow", "seasonal_direct_booking_promo"],
    integrationPrerequisites: ["Système PMS hôtelier ou calendrier", "Ligne téléphonique Telnyx"],
    regulatoryConstraintsFr: "Conformité sur la taxe sur l'hébergement et déclaration d'enregistrement touristique.",
    regulatoryConstraintsEn: "Lodging tax compliance and tourist establishment licensing.",
    featureAvailability: "available",
    demoSteps: [
      {
        stepNumber: 1,
        titleFr: "Appel de réservation en soirée",
        titleEn: "Evening Reservation Call",
        descriptionFr: "Un voyageur appelle à 22h pour réserver un chalet ce week-end",
        descriptionEn: "Traveler calls at 10 PM to check lodge availability for weekend",
        activeModule: "voice",
        inputData: "Appel : 2 nuitées, 2 adultes, options spa et animaux acceptés",
        simulatedOutput: "Voice IA répond immédiatement en français et anglais",
        visualMetric: "Disponibilité vérifiée",
      },
      {
        stepNumber: 2,
        titleFr: "Confirmation de la réservation",
        titleEn: "Stay Reservation Confirmation",
        descriptionFr: "Création de la réservation avec consignes d'arrivée",
        descriptionEn: "Reservation created with lockbox code and arrival guidelines",
        activeModule: "crm",
        inputData: "Chalet Le Sommet réservé pour vendredi et samedi",
        simulatedOutput: "Envoi instantané de la confirmation sécurisée",
        visualMetric: "Séjour réservé",
      },
      {
        stepNumber: 3,
        titleFr: "Préparation de l'accueil client",
        titleEn: "Guest Welcoming Notes",
        descriptionFr: "Les préférences du voyageur sont mémorisées dans son profil",
        descriptionEn: "Guest preferences logged for future direct bookings",
        activeModule: "crm",
        inputData: "Fiche client : préférence bois de chauffage et animaux",
        simulatedOutput: "Profil voyageur enrichi",
        visualMetric: "Profil à jour",
      },
      {
        stepNumber: 4,
        titleFr: "Synchronisation comptable du séjour",
        titleEn: "Revenue & Tax Ledgering",
        descriptionFr: "La facture d'hébergement est prête pour la clôture",
        descriptionEn: "Lodging transaction mapped to tax-compliant accounting entry",
        activeModule: "accounting",
        inputData: "Écriture préparatoire : hébergement + taxe séjour",
        simulatedOutput: "Livre comptable prêt pour exportation",
        visualMetric: "Comptabilité prête",
      },
    ],
  },
  {
    id: "professional_services",
    nameFr: "Services Professionnels & Conseil",
    nameEn: "Professional Services & Consulting",
    descriptionFr: "Consultants en gestion, cabinets d'ingénieurs, architectes et agences de design.",
    descriptionEn: "Management consultants, engineering firms, architects, and design agencies.",
    iconName: "Briefcase",
    recommendedModules: ["crm", "voice", "ocr", "accounting"],
    useCasesFr: [
      "Filtrage des appels d'affaires entrants et prise de messages qualifiés",
      "Suivi rigoureux des mandats, jalons contractuels et propositions d'honoraires",
      "Extraction OCR des notes de frais de déplacement et reçus de mission",
    ],
    useCasesEn: [
      "Executive inbound call screening and structured message intake",
      "Rigorous tracking of client mandates, proposals, and project milestones",
      "OCR capture of travel expense receipts and project disbursements",
    ],
    workflowTemplates: ["consulting_lead_qualification", "mandate_milestone_crm", "expense_disbursement_ocr"],
    integrationPrerequisites: ["Google Calendar consultant", "Ligne téléphonique d'affaires"],
    regulatoryConstraintsFr: "Confidentialité des mandats (secret professionnel / accords de non-divulgation).",
    regulatoryConstraintsEn: "Client confidentiality requirements and non-disclosure obligations.",
    featureAvailability: "available",
    demoSteps: [
      {
        stepNumber: 1,
        titleFr: "Appel entrant d'un client potentiel",
        titleEn: "Executive Inbound Call",
        descriptionFr: "Un directeur d'entreprise appelle pour une mission d'audit stratégique",
        descriptionEn: "Corporate executive calls requesting advisory engagement",
        activeModule: "voice",
        inputData: "Appel vocal : audit organisationnel, entreprise de 85 employés",
        simulatedOutput: "Voice IA qualifie le besoin, le délai et le décideur",
        visualMetric: "Mandat qualifié",
      },
      {
        stepNumber: 2,
        titleFr: "Planification de la consultation initiale",
        titleEn: "Discovery Call Booking",
        descriptionFr: "L'agent réserve un échange de cadrage avec l'associé principal",
        descriptionEn: "Agent schedules discovery session on senior partner calendar",
        activeModule: "crm",
        inputData: "Créneau fixé : Mardi prochain à 10h00",
        simulatedOutput: "Lien de visioconférence et confirmation transmis",
        visualMetric: "Cadrage planifié",
      },
      {
        stepNumber: 3,
        titleFr: "Numérisation des reçus de mission",
        titleEn: "Project Expense OCR",
        descriptionFr: "Un consultant dépose ses reçus de déplacement ferroviaire et hôtel",
        descriptionEn: "Consultant uploads business trip travel receipts",
        activeModule: "ocr",
        inputData: "3 reçus scannés : 640.20 $ de débours remboursables",
        simulatedOutput: "Extraction détaillée : TVA, devise, poste de dépense",
        visualMetric: "OCR 100% vérifié",
      },
      {
        stepNumber: 4,
        titleFr: "Rapprochement et imputation projet",
        titleEn: "Mandate Expense Ledger",
        descriptionFr: "Les débours sont rattachés au mandat client pour refacturation",
        descriptionEn: "Disbursements attached to client file for project billing",
        activeModule: "accounting",
        inputData: "Écriture de facturation prête",
        simulatedOutput: "Frais imputés au dossier · Prêt pour émission de facture",
        visualMetric: "Dossier prêt",
      },
    ],
  },
  {
    id: "accounting_firms",
    nameFr: "Cabinets Comptables & Fiscalistes",
    nameEn: "Accounting & Tax Practices",
    descriptionFr: "Comptables professionnels agréés (CPA), préparateurs d'impôts et conseillers fiscaux.",
    descriptionEn: "Certified public accountants (CPA), tax preparers, and bookkeeping practices.",
    iconName: "Calculator",
    recommendedModules: ["accounting", "ocr", "crm", "voice"],
    useCasesFr: [
      "Gestion des flux d'appels intenses en période fiscale (mars-avril)",
      "Collecte et extraction OCR des pièces justificatives, factures et T4/Relevé 1",
      "Suivi de l'état d'avancement des dossiers de clôture par client",
    ],
    useCasesEn: [
      "Handling heavy phone call surges during peak tax filing season",
      "Document intake and OCR parsing of client receipts and tax slips",
      "Client close tracking and missing document collection reminders",
    ],
    workflowTemplates: ["tax_season_call_handler", "tax_document_ocr_intake", "client_missing_doc_nudge"],
    integrationPrerequisites: ["Ligne Telnyx cabinet", "Google Calendar rendez-vous fiscaux"],
    regulatoryConstraintsFr: "Avis de non-certification : Avenqo fournit une assistance de préparation comptable sans se substituer à l'exercice d'un CPA certifié.",
    regulatoryConstraintsEn: "Non-certification notice: Avenqo provides workflow prep and does not replace certified CPA judgment.",
    featureAvailability: "available",
    demoSteps: [
      {
        stepNumber: 1,
        titleFr: "Appel client en période fiscale",
        titleEn: "Tax Season Phone Surge",
        descriptionFr: "Un client appelle pour connaître la date de remise de sa déclaration",
        descriptionEn: "Client calls asking about status of corporate tax filing",
        activeModule: "voice",
        inputData: "Appel : 'Mon dossier de déclaration fiscale 2025 est-il prêt ?'",
        simulatedOutput: "Voice IA identifie le client via son numéro vérifié",
        visualMetric: "Client authentifié",
      },
      {
        stepNumber: 2,
        titleFr: "Consultation du statut dans le CRM",
        titleEn: "File Status Retrieval",
        descriptionFr: "IA Central vérifie l'étape du dossier dans le cabinet",
        descriptionEn: "IA Central looks up progress stage in firm workspace",
        activeModule: "crm",
        inputData: "Vérification statut : 'En révision finale par le fiscaliste'",
        simulatedOutput: "L'agent informe le client et propose un point téléphonique",
        visualMetric: "Statut clair",
      },
      {
        stepNumber: 3,
        titleFr: "Traitement par lot de reçus clients",
        titleEn: "Batch Receipt OCR Ingestion",
        descriptionFr: "Téléversement d'un lot de 25 factures pour un client de tenue de livres",
        descriptionEn: "Bookkeeper drops 25 client expense slips for month-end",
        activeModule: "ocr",
        inputData: "25 documents traités en moins de 15 secondes",
        simulatedOutput: "Extraction automatique : dates, numéros de facture, taxes",
        visualMetric: "25/25 extraits",
      },
      {
        stepNumber: 4,
        titleFr: "Génération des écritures préparatoires",
        titleEn: "Accountant Ledger Prep",
        descriptionFr: "Export structuré pour injection dans le logiciel comptable",
        descriptionEn: "Structured entries ready for CPA verification and ledger import",
        activeModule: "accounting",
        inputData: "Écritures équilibrées générées avec mention d'assistance",
        simulatedOutput: "Gain de temps de saisie de 85% pour le cabinet",
        visualMetric: "Livre préparé",
      },
    ],
  },
  {
    id: "manufacturing_distribution",
    nameFr: "Industrie, Fabrication & Distribution",
    nameEn: "Manufacturing & Wholesale Distribution",
    descriptionFr: "Usines de fabrication, grossistes, distributeurs industriels et importateurs B2B.",
    descriptionEn: "Manufacturing plants, wholesalers, industrial distributors, and B2B importers.",
    iconName: "Factory",
    recommendedModules: ["retail", "ocr", "crm", "accounting"],
    useCasesFr: [
      "Analyse des volumes de commandes B2B et anticipation des réapprovisionnements matières",
      "Numérisation OCR des bons de commande clients complexes et manifestes d'expédition",
      "Gestion des comptes clients distributeurs et suivi des conditions tarifaires",
    ],
    useCasesEn: [
      "B2B order volume velocity and raw material replenishment forecasts",
      "OCR processing of complex purchase orders (PO) and shipping manifests",
      "Wholesale distributor CRM tracking negotiated payment terms and pricing",
    ],
    workflowTemplates: ["b2b_purchase_order_ocr", "wholesale_replenishment_forecast", "distributor_account_review"],
    integrationPrerequisites: ["Système ERP / tableurs d'inventaire", "Passerelle de facturation"],
    regulatoryConstraintsFr: "Traçabilité des lots et respect des normes industrielles applicables.",
    regulatoryConstraintsEn: "Batch lot traceability and industrial trade standards compliance.",
    featureAvailability: "available",
    demoSteps: [
      {
        stepNumber: 1,
        titleFr: "Réception d'un bon de commande B2B",
        titleEn: "B2B Purchase Order Ingestion",
        descriptionFr: "Un distributeur transmet un bon de commande PDF de 14 lignes d'articles",
        descriptionEn: "Distributor submits 14-line item purchase order PDF",
        activeModule: "ocr",
        inputData: "Bon de commande PDF de 45 200 $ reçu par courriel",
        simulatedOutput: "Extraction OCR : codes SKU, quantités, prix unitaires convenus",
        visualMetric: "14 lignes extraites",
      },
      {
        stepNumber: 2,
        titleFr: "Vérification des stocks disponibles",
        titleEn: "Inventory Sufficiency Check",
        descriptionFr: "Retail IA vérifie la disponibilité des pièces en entrepôt",
        descriptionEn: "Retail AI verifies warehouse stock balance for all 14 lines",
        activeModule: "retail",
        inputData: "Analyse stocks : 12 articles prêts, 2 en réassort dans 48h",
        simulatedOutput: "Calcul de la date de livraison garantie complète",
        visualMetric: "Stock vérifié",
      },
      {
        stepNumber: 3,
        titleFr: "Mise à jour de la fiche grand compte",
        titleEn: "Account Deal Update",
        descriptionFr: "Le CRM enregistre la commande confirmée au compte du distributeur",
        descriptionEn: "CRM records confirmed order on distributor ledger",
        activeModule: "crm",
        inputData: "Enregistrement commande #PO-9418",
        simulatedOutput: "Termes de paiement : Net 30 jours appliqués",
        visualMetric: "Commande enregistrée",
      },
      {
        stepNumber: 4,
        titleFr: "Génération de l'accusé de réception",
        titleEn: "Order Confirmation Dispatch",
        descriptionFr: "Confirmation automatique avec date d'expédition expédiée au client",
        descriptionEn: "Order confirmation and planned ship date dispatched to client",
        activeModule: "central_ai",
        inputData: "Accusé de réception formel envoyé",
        simulatedOutput: "Équipe d'entrepôt notifiée pour préparation de la commande",
        visualMetric: "Ordre lancé",
      },
    ],
  },
  {
    id: "service_companies",
    nameFr: "Entreprises de Services & Dépannage",
    nameEn: "Field Services & Maintenance",
    descriptionFr: "Services de nettoyage, sécurité, dépannage informatique, climatisation et paysagement.",
    descriptionEn: "Commercial cleaning, security patrol, IT repair, HVAC maintenance, and landscaping.",
    iconName: "ShieldCheck",
    recommendedModules: ["voice", "crm", "ocr", "marketing"],
    useCasesFr: [
      "Permanence téléphonique pour urgences de dépannage 24/7 avec routage immédiat",
      "Attribution des demandes d'intervention aux techniciens sur le terrain",
      "Facturation des interventions récurrentes et suivi des contrats annuels",
    ],
    useCasesEn: [
      "24/7 on-call dispatch handling urgent maintenance calls and triage",
      "Field technician job assignment and mobile dispatch tracking",
      "Recurring contract billing management and annual maintenance renewals",
    ],
    workflowTemplates: ["field_service_emergency_call", "technician_job_dispatch", "annual_maintenance_renewal"],
    integrationPrerequisites: ["Ligne de garde Telnyx", "Google Calendar techniciens"],
    regulatoryConstraintsFr: "Obligation de confirmation écrite des tarifs avant intervention d'urgence.",
    regulatoryConstraintsEn: "Mandatory disclosure of emergency rates before dispatch.",
    featureAvailability: "available",
    demoSteps: [
      {
        stepNumber: 1,
        titleFr: "Appel pour urgence climatisation / CVC",
        titleEn: "Urgent Service Call",
        descriptionFr: "Un gestionnaire d'immeuble appelle pour une panne de climatiseur en surchauffe",
        descriptionEn: "Building manager calls for urgent server room HVAC failure",
        activeModule: "voice",
        inputData: "Appel d'urgence : panne de climatisation, salle des serveurs",
        simulatedOutput: "L'agent vocal qualifie l'urgence critique et la localisation",
        visualMetric: "Urgence identifiée",
      },
      {
        stepNumber: 2,
        titleFr: "Sélection du technicien de garde",
        titleEn: "Technician Calendar Check",
        descriptionFr: "CRM IA vérifie qui est le technicien d'astreinte disponible dans la zone",
        descriptionEn: "CRM AI checks on-call technician schedule in geographic sector",
        activeModule: "crm",
        inputData: "Technicien Marc disponible à 25 minutes du site",
        simulatedOutput: "Créneau d'intervention bloqué à 11h15",
        visualMetric: "Technicien assigné",
      },
      {
        stepNumber: 3,
        titleFr: "Confirmation immédiate au client",
        titleEn: "Caller Status Update",
        descriptionFr: "L'agent rassure l'appelant et confirme l'arrivée du technicien",
        descriptionEn: "Voice agent confirms estimated technician arrival with caller",
        activeModule: "voice",
        inputData: "Avis verbal : technicien Marc en route, arrivée 11h15",
        simulatedOutput: "SMS de suivi transmis au gestionnaire",
        visualMetric: "Client rassuré",
      },
      {
        stepNumber: 4,
        titleFr: "Création du bon d'intervention",
        titleEn: "Service Ticket Generation",
        descriptionFr: "Le bon de travail complet est généré dans le CRM d'entreprise",
        descriptionEn: "Comprehensive ticket logged with notes and fault description",
        activeModule: "crm",
        inputData: "Fiche intervention #TK-551 créée",
        simulatedOutput: "Rapport prêt pour validation post-intervention",
        visualMetric: "Ticket actif",
      },
    ],
  },
  {
    id: "associations_nonprofit",
    nameFr: "Associations & Organismes sans but lucratif",
    nameEn: "Associations & Non-Profits",
    descriptionFr: "Organismes de bienfaisance, chambres de commerce, ordres professionnels et fondations.",
    descriptionEn: "Charitable organizations, chambers of commerce, non-profits, and foundations.",
    iconName: "Users",
    recommendedModules: ["crm", "marketing", "ocr", "accounting"],
    useCasesFr: [
      "Gestion des adhésions, cotisations et renouvellements annuels des membres",
      "Campagnes de sensibilisation et courriels d'invitation aux assemblées",
      "Extraction OCR des reçus de dons et justificatifs de subventions",
    ],
    useCasesEn: [
      "Member database management, annual renewals, and dues tracking",
      "Community outreach campaigns and AGM invitation broadcasts",
      "OCR processing of donation slips, receipts, and grant expense reports",
    ],
    workflowTemplates: ["membership_renewal_nudge", "donor_receipt_ocr", "community_event_invitation"],
    integrationPrerequisites: ["Passerelle de don ou paiements", "Base de contacts membres"],
    regulatoryConstraintsFr: "Conformité sur la gouvernance des OSBL et émission de reçus officiels de don.",
    regulatoryConstraintsEn: "Non-profit governance rules and official tax receipt standards.",
    featureAvailability: "available",
    demoSteps: [
      {
        stepNumber: 1,
        titleFr: "Gestion des renouvellements d'adhésion",
        titleEn: "Member Dues Renewal",
        descriptionFr: "Identification des membres arrivant à échéance de cotisation",
        descriptionEn: "System checks members whose annual membership expires this month",
        activeModule: "crm",
        inputData: "Filtre CRM : 86 adhésions à renouveler ce mois-ci",
        simulatedOutput: "Liste segmentée prête pour communication personnalisée",
        visualMetric: "86 membres ciblés",
      },
      {
        stepNumber: 2,
        titleFr: "Préparation du message de courtoisie",
        titleEn: "Friendly Renewal Campaign",
        descriptionFr: "Marketing IA rédige un message chaleureux rappelant l'impact des actions",
        descriptionEn: "Marketing AI crafts warm reminder letter highlighting yearly impact",
        activeModule: "marketing",
        inputData: "Texte personnalisé selon le niveau d'adhésion",
        simulatedOutput: "Soumis à l'approbation du conseil d'administration",
        visualMetric: "Brouillon prêt",
      },
      {
        stepNumber: 3,
        titleFr: "Validation humaine du message",
        titleEn: "Board Approval Validation",
        descriptionFr: "Le directeur général approuve la diffusion",
        descriptionEn: "Executive director signs off on the outreach communication",
        activeModule: "central_ai",
        inputData: "Validation administrative effectuée",
        simulatedOutput: "Envoi planifié sans sollicitation agressive",
        visualMetric: "Action approuvée",
      },
      {
        stepNumber: 4,
        titleFr: "Numérisation des reçus de don",
        titleEn: "Donation Receipt OCR",
        descriptionFr: "Numérisation des bordereaux de dons reçus par la poste",
        descriptionEn: "Intake of paper donation slips received at community office",
        activeModule: "ocr",
        inputData: "Lots de dons numérisés avec attribution aux donateurs",
        simulatedOutput: "Extraction des montants pour production du reçu fiscal",
        visualMetric: "Dons enregistrés",
      },
    ],
  },
  {
    id: "other_custom",
    nameFr: "Autre secteur d'activité",
    nameEn: "Other Custom Sector",
    descriptionFr: "Entreprise ou activité spécifique : configurez votre secteur sur mesure avec vos propres processus.",
    descriptionEn: "Specialized business model: configure your custom industry profile tailored to your unique operations.",
    iconName: "Sparkles",
    recommendedModules: ["crm", "voice", "retail", "accounting", "marketing", "ocr"],
    useCasesFr: [
      "Personnalisation intégrale des modules selon vos processus opérationnels uniques",
      "Orchestration IA Central sur mesure reliant vos outils et vos équipes",
      "Démonstration synthétique guidée avec vos cas d'usages spécifiques",
    ],
    useCasesEn: [
      "Full module customization configured around your unique business operations",
      "Custom IA Central orchestration connecting your team and external tools",
      "Guided synthetic demonstration adapted to your explicit operating model",
    ],
    workflowTemplates: ["custom_business_automation", "central_ai_orchestration"],
    integrationPrerequisites: ["Selon les modules choisis"],
    regulatoryConstraintsFr: "Application stricte des règles de sécurité, de confidentialité et des permissions en vigueur.",
    regulatoryConstraintsEn: "Strict application of active security, privacy, and permission controls.",
    featureAvailability: "available",
    demoSteps: [
      {
        stepNumber: 1,
        titleFr: "Expression du besoin métier",
        titleEn: "Custom Business Requirement",
        descriptionFr: "Le client décrit son modèle d'exploitation personnalisé",
        descriptionEn: "User describes their unique operating model and customer journey",
        activeModule: "central_ai",
        inputData: "Description : modèle hybride avec rendez-vous et vente directe",
        simulatedOutput: "Analyse par IA Central des flux opérationnels",
        visualMetric: "Profil analysé",
      },
      {
        stepNumber: 2,
        titleFr: "Recommandation modulaire adaptée",
        titleEn: "Tailored Modular Fit",
        descriptionFr: "Sélection des modules essentiels pour respecter le budget et le forfait",
        descriptionEn: "Recommended module combination fitting the chosen subscription tier",
        activeModule: "central_ai",
        inputData: "Modules suggérés : CRM IA + Voice IA (Forfait Base)",
        simulatedOutput: "Allocation exacte de 2 modules sans dépassement de forfait",
        visualMetric: "Configuration exacte",
      },
      {
        stepNumber: 3,
        titleFr: "Simulation du parcours de travail",
        titleEn: "Simulated Workflow Journey",
        descriptionFr: "Démonstration interactive démontrant la synergie des modules sélectionnés",
        descriptionEn: "Interactive demonstration showcasing coordination between modules",
        activeModule: "crm",
        inputData: "Coordination fluide entre réception et gestion des dossiers",
        simulatedOutput: "Zéro friction · Processus documenté de bout en bout",
        visualMetric: "Parcours validé",
      },
      {
        stepNumber: 4,
        titleFr: "Espace entreprise prêt pour activation",
        titleEn: "Workspace Ready for Activation",
        descriptionFr: "Création de l'espace avec paramètres personnalisés",
        descriptionEn: "Company workspace created with dedicated custom industry profile",
        activeModule: "central_ai",
        inputData: "Environnement multi-tenant isolé généré",
        simulatedOutput: "Accompagnement guidé pour la première valeur vérifiée",
        visualMetric: "Espace prêt",
      },
    ],
  },
];

export const SECTOR_PROFILES_BY_ID = Object.fromEntries(
  SECTOR_PROFILES.map((p) => [p.id, p])
);

export function getSectorProfile(id: string): SectorProfile {
  return SECTOR_PROFILES_BY_ID[id] ?? SECTOR_PROFILES_BY_ID["other_custom"];
}
