"""Validate and generate the Web and Flutter locale representations."""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / "shared" / "locales" / "canonical_locales.json"
WEB_OUTPUT = ROOT / "web" / "src" / "lib" / "i18n" / "canonical-locales.generated.ts"
FLUTTER_OUTPUT = ROOT / "frontend" / "assets" / "i18n" / "_locales.json"


def load_locales() -> list[dict[str, str]]:
    locales = json.loads(SOURCE.read_text(encoding="utf-8"))
    if len(locales) != 44:
        raise SystemExit(f"Canonical locale count must be 44, got {len(locales)}")
    codes = [locale["code"] for locale in locales]
    if len(codes) != len(set(codes)):
        raise SystemExit("Canonical locale codes must be unique")
    required = {"code", "bcp47", "region", "flag", "nativeName", "englishName", "direction", "fallback"}
    for locale in locales:
        missing = required - locale.keys()
        if missing:
            raise SystemExit(f"{locale.get('code', '<unknown>')} missing {sorted(missing)}")
        if locale["direction"] not in {"ltr", "rtl"}:
            raise SystemExit(f"Invalid direction for {locale['code']}")
        if locale["fallback"] not in codes:
            raise SystemExit(f"Invalid fallback for {locale['code']}")
        if not (ROOT / "frontend" / "assets" / "i18n" / f"{locale['code']}.json").exists():
            raise SystemExit(f"Missing translation asset for {locale['code']}")
    return locales


def generate(locales: list[dict[str, str]]) -> None:
    web_entries = [
        {
            "code": locale["code"],
            "bcp47": locale["bcp47"],
            "region": locale["region"],
            "flag": locale["flag"],
            "nativeName": locale["nativeName"],
            "englishName": locale["englishName"],
            "direction": locale["direction"],
            "currency": locale["currency"],
            "timezone": locale["timezone"],
        }
        for locale in locales
    ]
    WEB_OUTPUT.write_text(
        "/* Generated by shared/locales/generate_contract.py. Do not edit manually. */\n"
        "import type { LocaleDefinition } from \"./types\";\n\n"
        f"export const CANONICAL_LOCALES: LocaleDefinition[] = {json.dumps(web_entries, ensure_ascii=False, indent=2)};\n",
        encoding="utf-8",
    )
    FLUTTER_OUTPUT.write_text(
        json.dumps(
            [
                {
                    "code": locale["code"],
                    "bcp47": locale["bcp47"],
                    "region": locale["region"],
                    "flag": locale["flag"],
                    "nativeName": locale["nativeName"],
                    "englishName": locale["englishName"],
                    "direction": locale["direction"],
                    "currency": locale["currency"],
                    "timezone": locale["timezone"],
                }
                for locale in locales
            ],
            ensure_ascii=False,
            indent=2,
        )
        + "\n",
        encoding="utf-8",
    )


if __name__ == "__main__":
    canonical = load_locales()
    generate(canonical)
    print(f"Generated canonical locale contract: {len(canonical)}/44")
