/* Generated by scripts/generate-app-catalogs.mjs. Do not edit manually. */
import type { LocaleCode } from "./types";
import catalogs from "./application-catalogs.generated.json";

export type ApplicationCatalog = (typeof catalogs)["en"];
export const APPLICATION_CATALOGS: Record<LocaleCode, ApplicationCatalog> = catalogs;

export function getApplicationCatalog(locale: LocaleCode | string): ApplicationCatalog {
  return APPLICATION_CATALOGS[locale as LocaleCode] ?? APPLICATION_CATALOGS.en;
}
