/* Generated by scripts/generate-app-catalogs.mjs. Do not edit manually. */
import type { LocaleCode } from "./types";
import messages from "./voice-auth-messages.generated.json";

export const VOICE_AUTH_MESSAGES: Record<LocaleCode, readonly string[]> = messages;
