"""Localized public API error messages without changing the response schema."""

from __future__ import annotations

from functools import lru_cache
import json
from pathlib import Path

from backend.app.core.locale_catalog import LOCALES

_MESSAGE_KEYS = (
    "request_invalid",
    "validation_failed",
    "required_field",
    "invalid_value",
    "authentication_required",
    "subscription_required",
    "permission_denied",
    "not_found",
    "conflict",
    "rate_limited",
    "service_unavailable",
    "internal_error",
)

_AGENT_UPGRADE_MESSAGES = {
    "en": "This agent is not enabled for your account. Review your modules and plan options in Billing.",
    "fr": "Cet agent n’est pas activé pour votre compte. Consultez vos modules et les offres dans Facturation.",
    "es": "Este agente no está activado para tu cuenta. Consulta los módulos y planes en Facturación.",
    "pt": "Este agente não está ativo na sua conta. Consulte os módulos e planos em Faturação.",
    "ro": "Acest agent nu este activat pentru contul dvs. Consultați modulele și planurile în Facturare.",
    "de": "Dieser Agent ist für Ihr Konto nicht aktiviert. Prüfen Sie Module und Tarife unter Abrechnung.",
    "it": "Questo agente non è attivo per il tuo account. Consulta moduli e piani in Fatturazione.",
    "nl": "Deze agent is niet geactiveerd voor uw account. Bekijk modules en abonnementen bij Facturering.",
    "pl": "Ten agent nie jest aktywny na Twoim koncie. Sprawdź moduły i plany w Rozliczeniach.",
    "ru": "Этот агент не активирован для вашей учётной записи. Посмотрите модули и тарифы в разделе оплаты.",
    "uk": "Цей агент не активований для вашого облікового запису. Перегляньте модулі й тарифи в розділі оплати.",
    "el": "Αυτός ο πράκτορας δεν είναι ενεργός για τον λογαριασμό σας. Δείτε τις ενότητες και τα πακέτα στη Χρέωση.",
    "sv": "Denna agent är inte aktiverad för ditt konto. Se moduler och abonnemang under Fakturering.",
    "tr": "Bu aracı hesabınızda etkin değil. Faturalandırma bölümünde modülleri ve planları inceleyin.",
    "cs": "Tento agent není pro váš účet aktivní. Zkontrolujte moduly a tarify ve Fakturaci.",
    "ar": "هذا الوكيل غير مفعّل لحسابك. راجع الوحدات والخطط في الفوترة.",
    "he": "סוכן זה אינו מופעל בחשבונך. בדוק מודולים ותוכניות בחיוב.",
    "fa": "این عامل برای حساب شما فعال نیست. ماژول‌ها و طرح‌ها را در صورتحساب بررسی کنید.",
    "ja": "このエージェントはアカウントで有効になっていません。請求画面でモジュールとプランを確認してください。",
    "ko": "이 에이전트는 계정에서 활성화되지 않았습니다. 청구에서 모듈과 요금제를 확인하세요.",
    "zh": "此代理尚未在您的账户中启用。请在账单中查看模块和套餐。",
    "ka": "ეს აგენტი თქვენი ანგარიშისთვის აქტიური არ არის. მოდულები და გეგმები ნახეთ ანგარიშსწორებაში.",
    "hy": "Այս գործակալը ձեր հաշվի համար ակտիվ չէ։ Դիտեք մոդուլներն ու պլանները Վճարումներում։",
    "sw": "Wakala huyu hajawezeshwa kwa akaunti yako. Angalia moduli na mipango kwenye Malipo.",
    "am": "ይህ ወኪል ለመለያዎ አልነቃም። ሞጁሎችንና ዕቅዶችን በክፍያ ይመልከቱ።",
    "af": "Hierdie agent is nie vir jou rekening geaktiveer nie. Sien modules en planne onder Fakturering.",
    "ha": "Ba a kunna wannan wakili don asusunka ba. Duba kayayyaki da tsare-tsare a sashen Biyan kuɗi.",
    "hi": "यह एजेंट आपके खाते के लिए सक्रिय नहीं है। बिलिंग में मॉड्यूल और योजनाएँ देखें।",
    "bn": "এই এজেন্ট আপনার অ্যাকাউন্টে সক্রিয় নয়। বিলিংয়ে মডিউল এবং পরিকল্পনা দেখুন।",
    "ur": "یہ ایجنٹ آپ کے اکاؤنٹ کے لیے فعال نہیں ہے۔ بلنگ میں ماڈیولز اور منصوبے دیکھیں۔",
    "ta": "இந்த முகவர் உங்கள் கணக்கில் செயல்படுத்தப்படவில்லை. கட்டணப் பகுதியில் தொகுதிகளையும் திட்டங்களையும் பார்க்கவும்.",
    "pa": "ਇਹ ਏਜੰਟ ਤੁਹਾਡੇ ਖਾਤੇ ਲਈ ਸਰਗਰਮ ਨਹੀਂ ਹੈ। ਬਿਲਿੰਗ ਵਿੱਚ ਮੋਡੀਊਲ ਅਤੇ ਯੋਜਨਾਵਾਂ ਦੇਖੋ।",
    "ne": "यो एजेन्ट तपाईंको खातामा सक्रिय छैन। बिलिङमा मोड्युल र योजनाहरू हेर्नुहोस्।",
    "vi": "Tác nhân này chưa được bật cho tài khoản. Xem mô-đun và gói trong Thanh toán.",
    "th": "เอเจนต์นี้ยังไม่เปิดใช้งานสำหรับบัญชีของคุณ ตรวจสอบโมดูลและแพ็กเกจในการเรียกเก็บเงิน",
    "id": "Agen ini belum diaktifkan untuk akun Anda. Lihat modul dan paket di Penagihan.",
    "ms": "Ejen ini belum diaktifkan untuk akaun anda. Semak modul dan pelan dalam Pengebilan.",
    "tl": "Hindi pa aktibo ang agent na ito sa iyong account. Tingnan ang mga module at plano sa Pagsingil.",
    "my": "ဤအေးဂျင့်ကို သင့်အကောင့်အတွက် မဖွင့်ထားပါ။ ငွေတောင်းခံမှုတွင် မော်ဂျူးများနှင့် အစီအစဉ်များကို ကြည့်ပါ။",
    "km": "ភ្នាក់ងារនេះមិនទាន់សកម្មសម្រាប់គណនីអ្នកទេ។ ពិនិត្យម៉ូឌុលនិងគម្រោងក្នុងការចេញវិក្កយបត្រ។",
    "mn": "Энэ агент таны дансанд идэвхжээгүй байна. Төлбөр хэсгээс модулиуд болон багцуудыг үзнэ үү.",
}


def agent_upgrade_message(locale: str) -> str:
    language = resolve_api_locale(locale).split("-")[0]
    return _AGENT_UPGRADE_MESSAGES[language] + " /billing"

_MESSAGES_BY_LANGUAGE: dict[str, tuple[str, ...]] = {
    "en": (
        "The request could not be processed. Check the submitted information.",
        "Some submitted information is invalid.",
        "This field is required.",
        "This value is invalid.",
        "Authentication is required. Please sign in again.",
        "An active subscription is required.",
        "You do not have permission to perform this action.",
        "The requested resource could not be found.",
        "This request conflicts with current data.",
        "Too many requests. Please try again later.",
        "This service is temporarily unavailable. Please try again later.",
        "An unexpected error occurred. Please try again.",
    ),
    "fr": (
        "La demande n’a pas pu être traitée. Vérifiez les informations fournies.",
        "Certaines informations fournies sont invalides.",
        "Ce champ est obligatoire.",
        "Cette valeur est invalide.",
        "Authentification requise. Veuillez vous reconnecter.",
        "Un abonnement actif est requis.",
        "Accès non autorisé pour cette action.",
        "La ressource demandée est introuvable.",
        "Cette demande entre en conflit avec les données actuelles.",
        "Trop de requêtes. Veuillez réessayer plus tard.",
        "Ce service est temporairement indisponible. Veuillez réessayer plus tard.",
        "Une erreur inattendue est survenue. Veuillez réessayer.",
    ),
    "es": (
        "No se pudo procesar la solicitud. Comprueba la información enviada.",
        "Algunos datos enviados no son válidos.",
        "Este campo es obligatorio.",
        "Este valor no es válido.",
        "Se requiere autenticación. Inicia sesión de nuevo.",
        "Se requiere una suscripción activa.",
        "No tienes permiso para realizar esta acción.",
        "No se encontró el recurso solicitado.",
        "Esta solicitud entra en conflicto con los datos actuales.",
        "Demasiadas solicitudes. Inténtalo de nuevo más tarde.",
        "El servicio no está disponible temporalmente. Inténtalo de nuevo más tarde.",
        "Se produjo un error inesperado. Inténtalo de nuevo.",
    ),
    "pt": (
        "Não foi possível processar a solicitação. Verifique as informações enviadas.",
        "Algumas informações enviadas são inválidas.",
        "Este campo é obrigatório.",
        "Este valor é inválido.",
        "É necessário autenticar-se. Inicie sessão novamente.",
        "É necessária uma subscrição ativa.",
        "Não tem permissão para executar esta ação.",
        "O recurso solicitado não foi encontrado.",
        "Esta solicitação entra em conflito com os dados atuais.",
        "Demasiadas solicitações. Tente novamente mais tarde.",
        "O serviço está temporariamente indisponível. Tente novamente mais tarde.",
        "Ocorreu um erro inesperado. Tente novamente.",
    ),
    "ro": (
        "Solicitarea nu a putut fi procesată. Verificați informațiile trimise.",
        "Unele informații trimise sunt invalide.",
        "Acest câmp este obligatoriu.",
        "Această valoare este invalidă.",
        "Autentificarea este necesară. Conectați-vă din nou.",
        "Este necesar un abonament activ.",
        "Nu aveți permisiunea de a efectua această acțiune.",
        "Resursa solicitată nu a fost găsită.",
        "Solicitarea intră în conflict cu datele curente.",
        "Prea multe solicitări. Încercați din nou mai târziu.",
        "Serviciul este temporar indisponibil. Încercați din nou mai târziu.",
        "A apărut o eroare neașteptată. Încercați din nou.",
    ),
    "de": (
        "Die Anfrage konnte nicht verarbeitet werden. Prüfen Sie Ihre Angaben.",
        "Einige der übermittelten Angaben sind ungültig.",
        "Dieses Feld ist erforderlich.",
        "Dieser Wert ist ungültig.",
        "Eine Anmeldung ist erforderlich. Bitte melden Sie sich erneut an.",
        "Ein aktives Abonnement ist erforderlich.",
        "Sie sind nicht berechtigt, diese Aktion auszuführen.",
        "Die angeforderte Ressource wurde nicht gefunden.",
        "Diese Anfrage steht im Konflikt mit den aktuellen Daten.",
        "Zu viele Anfragen. Bitte versuchen Sie es später erneut.",
        "Der Dienst ist vorübergehend nicht verfügbar. Bitte versuchen Sie es später erneut.",
        "Ein unerwarteter Fehler ist aufgetreten. Bitte versuchen Sie es erneut.",
    ),
    "it": (
        "Impossibile elaborare la richiesta. Controlla le informazioni inviate.",
        "Alcune informazioni inviate non sono valide.",
        "Questo campo è obbligatorio.",
        "Questo valore non è valido.",
        "È necessaria l’autenticazione. Accedi di nuovo.",
        "È necessario un abbonamento attivo.",
        "Non hai l’autorizzazione per eseguire questa azione.",
        "La risorsa richiesta non è stata trovata.",
        "Questa richiesta è in conflitto con i dati correnti.",
        "Troppe richieste. Riprova più tardi.",
        "Il servizio non è temporaneamente disponibile. Riprova più tardi.",
        "Si è verificato un errore imprevisto. Riprova.",
    ),
    "nl": (
        "Het verzoek kon niet worden verwerkt. Controleer de ingevoerde gegevens.",
        "Sommige ingevoerde gegevens zijn ongeldig.",
        "Dit veld is verplicht.",
        "Deze waarde is ongeldig.",
        "Authenticatie is vereist. Meld u opnieuw aan.",
        "Een actief abonnement is vereist.",
        "U hebt geen toestemming om deze actie uit te voeren.",
        "De gevraagde bron is niet gevonden.",
        "Dit verzoek is in conflict met de huidige gegevens.",
        "Te veel verzoeken. Probeer het later opnieuw.",
        "Deze service is tijdelijk niet beschikbaar. Probeer het later opnieuw.",
        "Er is een onverwachte fout opgetreden. Probeer het opnieuw.",
    ),
    "pl": (
        "Nie można przetworzyć żądania. Sprawdź przesłane informacje.",
        "Niektóre przesłane informacje są nieprawidłowe.",
        "To pole jest wymagane.",
        "Ta wartość jest nieprawidłowa.",
        "Wymagane jest uwierzytelnienie. Zaloguj się ponownie.",
        "Wymagana jest aktywna subskrypcja.",
        "Nie masz uprawnień do wykonania tej czynności.",
        "Nie znaleziono żądanego zasobu.",
        "To żądanie jest sprzeczne z bieżącymi danymi.",
        "Zbyt wiele żądań. Spróbuj ponownie później.",
        "Usługa jest tymczasowo niedostępna. Spróbuj ponownie później.",
        "Wystąpił nieoczekiwany błąd. Spróbuj ponownie.",
    ),
    "ru": (
        "Не удалось обработать запрос. Проверьте отправленные данные.",
        "Некоторые отправленные данные недействительны.",
        "Это поле обязательно.",
        "Это значение недействительно.",
        "Требуется аутентификация. Войдите в систему снова.",
        "Требуется активная подписка.",
        "У вас нет разрешения на это действие.",
        "Запрошенный ресурс не найден.",
        "Этот запрос конфликтует с текущими данными.",
        "Слишком много запросов. Повторите попытку позже.",
        "Сервис временно недоступен. Повторите попытку позже.",
        "Произошла непредвиденная ошибка. Повторите попытку.",
    ),
    "uk": (
        "Не вдалося обробити запит. Перевірте надіслані дані.",
        "Деякі надіслані дані недійсні.",
        "Це поле обов’язкове.",
        "Це значення недійсне.",
        "Потрібна автентифікація. Увійдіть знову.",
        "Потрібна активна підписка.",
        "Ви не маєте дозволу виконувати цю дію.",
        "Запитаний ресурс не знайдено.",
        "Цей запит конфліктує з поточними даними.",
        "Забагато запитів. Спробуйте ще раз пізніше.",
        "Служба тимчасово недоступна. Спробуйте ще раз пізніше.",
        "Сталася неочікувана помилка. Спробуйте ще раз.",
    ),
    "el": (
        "Δεν ήταν δυνατή η επεξεργασία του αιτήματος. Ελέγξτε τα στοιχεία που υποβάλατε.",
        "Ορισμένα στοιχεία που υποβλήθηκαν δεν είναι έγκυρα.",
        "Αυτό το πεδίο είναι υποχρεωτικό.",
        "Αυτή η τιμή δεν είναι έγκυρη.",
        "Απαιτείται έλεγχος ταυτότητας. Συνδεθείτε ξανά.",
        "Απαιτείται ενεργή συνδρομή.",
        "Δεν έχετε άδεια να εκτελέσετε αυτήν την ενέργεια.",
        "Ο ζητούμενος πόρος δεν βρέθηκε.",
        "Αυτό το αίτημα έρχεται σε διένεξη με τα τρέχοντα δεδομένα.",
        "Πάρα πολλά αιτήματα. Δοκιμάστε ξανά αργότερα.",
        "Η υπηρεσία δεν είναι προσωρινά διαθέσιμη. Δοκιμάστε ξανά αργότερα.",
        "Παρουσιάστηκε μη αναμενόμενο σφάλμα. Δοκιμάστε ξανά.",
    ),
    "sv": (
        "Begäran kunde inte behandlas. Kontrollera de inskickade uppgifterna.",
        "Vissa inskickade uppgifter är ogiltiga.",
        "Det här fältet är obligatoriskt.",
        "Det här värdet är ogiltigt.",
        "Autentisering krävs. Logga in igen.",
        "En aktiv prenumeration krävs.",
        "Du har inte behörighet att utföra den här åtgärden.",
        "Den begärda resursen hittades inte.",
        "Begäran står i konflikt med aktuella data.",
        "För många förfrågningar. Försök igen senare.",
        "Tjänsten är tillfälligt otillgänglig. Försök igen senare.",
        "Ett oväntat fel inträffade. Försök igen.",
    ),
    "tr": (
        "İstek işlenemedi. Gönderilen bilgileri kontrol edin.",
        "Gönderilen bilgilerin bazıları geçersiz.",
        "Bu alan zorunludur.",
        "Bu değer geçersiz.",
        "Kimlik doğrulaması gerekiyor. Lütfen yeniden giriş yapın.",
        "Etkin bir abonelik gerekiyor.",
        "Bu işlemi gerçekleştirme izniniz yok.",
        "İstenen kaynak bulunamadı.",
        "Bu istek mevcut verilerle çakışıyor.",
        "Çok fazla istek gönderildi. Lütfen daha sonra tekrar deneyin.",
        "Hizmet geçici olarak kullanılamıyor. Lütfen daha sonra tekrar deneyin.",
        "Beklenmeyen bir hata oluştu. Lütfen tekrar deneyin.",
    ),
    "cs": (
        "Požadavek se nepodařilo zpracovat. Zkontrolujte zadané údaje.",
        "Některé zadané údaje jsou neplatné.",
        "Toto pole je povinné.",
        "Tato hodnota je neplatná.",
        "Je vyžadováno ověření. Přihlaste se znovu.",
        "Je vyžadováno aktivní předplatné.",
        "K provedení této akce nemáte oprávnění.",
        "Požadovaný prostředek nebyl nalezen.",
        "Tento požadavek je v konfliktu s aktuálními daty.",
        "Příliš mnoho požadavků. Zkuste to znovu později.",
        "Služba je dočasně nedostupná. Zkuste to znovu později.",
        "Došlo k neočekávané chybě. Zkuste to znovu.",
    ),
    "ka": (
        "მოთხოვნის დამუშავება ვერ მოხერხდა. შეამოწმეთ შეყვანილი ინფორმაცია.",
        "შეყვანილი ინფორმაციის ნაწილი არასწორია.",
        "ეს ველი სავალდებულოა.",
        "ეს მნიშვნელობა არასწორია.",
        "საჭიროა ავთენტიფიკაცია. ხელახლა შედით სისტემაში.",
        "საჭიროა აქტიური გამოწერა.",
        "ამ მოქმედების შესრულების უფლება არ გაქვთ.",
        "მოთხოვნილი რესურსი ვერ მოიძებნა.",
        "მოთხოვნა მიმდინარე მონაცემებთან კონფლიქტშია.",
        "მოთხოვნები ზედმეტად ხშირია. სცადეთ მოგვიანებით.",
        "სერვისი დროებით მიუწვდომელია. სცადეთ მოგვიანებით.",
        "მოხდა მოულოდნელი შეცდომა. სცადეთ ხელახლა.",
    ),
    "hy": (
        "Հարցումը չհաջողվեց մշակել։ Ստուգեք ուղարկված տվյալները։",
        "Ուղարկված որոշ տվյալներ անվավեր են։",
        "Այս դաշտը պարտադիր է։",
        "Այս արժեքն անվավեր է։",
        "Պահանջվում է նույնականացում։ Կրկին մուտք գործեք։",
        "Պահանջվում է ակտիվ բաժանորդագրություն։",
        "Դուք այս գործողությունը կատարելու թույլտվություն չունեք։",
        "Պահանջվող ռեսուրսը չի գտնվել։",
        "Հարցումը հակասում է ընթացիկ տվյալներին։",
        "Հարցումները չափազանց շատ են։ Փորձեք ավելի ուշ։",
        "Ծառայությունը ժամանակավորապես անհասանելի է։ Փորձեք ավելի ուշ։",
        "Անսպասելի սխալ է տեղի ունեցել։ Փորձեք կրկին։",
    ),
    "ar": (
        "تعذرت معالجة الطلب. تحقق من المعلومات المُرسلة.",
        "بعض المعلومات المُرسلة غير صالحة.",
        "هذا الحقل مطلوب.",
        "هذه القيمة غير صالحة.",
        "المصادقة مطلوبة. يُرجى تسجيل الدخول مجددًا.",
        "يلزم اشتراك نشط.",
        "ليست لديك صلاحية لتنفيذ هذا الإجراء.",
        "تعذر العثور على المورد المطلوب.",
        "يتعارض هذا الطلب مع البيانات الحالية.",
        "طلبات كثيرة جدًا. يُرجى المحاولة لاحقًا.",
        "الخدمة غير متاحة مؤقتًا. يُرجى المحاولة لاحقًا.",
        "حدث خطأ غير متوقع. يُرجى المحاولة مجددًا.",
    ),
    "he": (
        "לא ניתן לעבד את הבקשה. יש לבדוק את הפרטים שנשלחו.",
        "חלק מהפרטים שנשלחו אינם תקינים.",
        "שדה זה הוא שדה חובה.",
        "ערך זה אינו תקין.",
        "נדרש אימות. יש להתחבר שוב.",
        "נדרש מינוי פעיל.",
        "אין לך הרשאה לבצע פעולה זו.",
        "המשאב המבוקש לא נמצא.",
        "הבקשה מתנגשת עם הנתונים הנוכחיים.",
        "נשלחו יותר מדי בקשות. יש לנסות שוב מאוחר יותר.",
        "השירות אינו זמין כרגע. יש לנסות שוב מאוחר יותר.",
        "אירעה שגיאה בלתי צפויה. יש לנסות שוב.",
    ),
    "fa": (
        "پردازش درخواست ممکن نشد. اطلاعات ارسال‌شده را بررسی کنید.",
        "برخی از اطلاعات ارسال‌شده نامعتبر هستند.",
        "این فیلد الزامی است.",
        "این مقدار نامعتبر است.",
        "احراز هویت لازم است. دوباره وارد شوید.",
        "اشتراک فعال لازم است.",
        "اجازه انجام این کار را ندارید.",
        "منبع درخواستی پیدا نشد.",
        "این درخواست با داده‌های فعلی تداخل دارد.",
        "تعداد درخواست‌ها بیش از حد است. بعداً دوباره تلاش کنید.",
        "این سرویس موقتاً در دسترس نیست. بعداً دوباره تلاش کنید.",
        "خطای غیرمنتظره‌ای رخ داد. دوباره تلاش کنید.",
    ),
    "sw": (
        "Ombi halikuweza kuchakatwa. Kagua maelezo uliyotuma.",
        "Baadhi ya maelezo yaliyotumwa si sahihi.",
        "Sehemu hii inahitajika.",
        "Thamani hii si sahihi.",
        "Uthibitishaji unahitajika. Ingia tena.",
        "Usajili unaotumika unahitajika.",
        "Huna ruhusa ya kutekeleza kitendo hiki.",
        "Rasilimali iliyoombwa haikupatikana.",
        "Ombi hili linakinzana na data ya sasa.",
        "Maombi ni mengi mno. Jaribu tena baadaye.",
        "Huduma haipatikani kwa muda. Jaribu tena baadaye.",
        "Hitilafu isiyotarajiwa imetokea. Jaribu tena.",
    ),
    "am": (
        "ጥያቄውን ማስኬድ አልተቻለም። የላኩትን መረጃ ያረጋግጡ።",
        "ከተላከው መረጃ ውስጥ አንዳንዱ ልክ አይደለም።",
        "ይህ መስክ ያስፈልጋል።",
        "ይህ እሴት ልክ አይደለም።",
        "ማረጋገጫ ያስፈልጋል። እንደገና ይግቡ።",
        "ንቁ ምዝገባ ያስፈልጋል።",
        "ይህን እርምጃ ለመፈጸም ፈቃድ የለዎትም።",
        "የተጠየቀው መረጃ አልተገኘም።",
        "ይህ ጥያቄ ከአሁኑ መረጃ ጋር ይጋጫል።",
        "ብዙ ጥያቄዎች ተልከዋል። ቆይተው ይሞክሩ።",
        "አገልግሎቱ ለጊዜው አይገኝም። ቆይተው ይሞክሩ።",
        "ያልተጠበቀ ስህተት ተከስቷል። እንደገና ይሞክሩ።",
    ),
    "af": (
        "Die versoek kon nie verwerk word nie. Kontroleer die ingediende inligting.",
        "Sommige ingediende inligting is ongeldig.",
        "Hierdie veld is verpligtend.",
        "Hierdie waarde is ongeldig.",
        "Verifikasie word vereis. Meld asseblief weer aan.",
        "’n Aktiewe intekening word vereis.",
        "Jy is nie gemagtig om hierdie handeling uit te voer nie.",
        "Die aangevraagde hulpbron kon nie gevind word nie.",
        "Hierdie versoek bots met die huidige data.",
        "Te veel versoeke. Probeer asseblief later weer.",
        "Die diens is tydelik nie beskikbaar nie. Probeer asseblief later weer.",
        "’n Onverwagte fout het voorgekom. Probeer asseblief weer.",
    ),
    "ha": (
        "Ba a iya sarrafa buƙatar ba. Duba bayanan da aka aika.",
        "Wasu bayanan da aka aika ba su da inganci.",
        "Ana buƙatar wannan filin.",
        "Wannan ƙimar ba ta da inganci.",
        "Ana buƙatar tantancewa. Sake shiga.",
        "Ana buƙatar rajista mai aiki.",
        "Ba ka da izinin yin wannan aikin.",
        "Ba a sami albarkatun da aka nema ba.",
        "Wannan buƙatar ta ci karo da bayanan yanzu.",
        "An aika buƙatu da yawa. Sake gwadawa daga baya.",
        "Sabis ɗin ba ya samuwa na ɗan lokaci. Sake gwadawa daga baya.",
        "An sami kuskure da ba a zata ba. Sake gwadawa.",
    ),
    "zh": (
        "无法处理此请求。请检查提交的信息。",
        "提交的信息中有些内容无效。",
        "此字段为必填项。",
        "此值无效。",
        "需要进行身份验证。请重新登录。",
        "需要有效的订阅。",
        "你没有执行此操作的权限。",
        "找不到请求的资源。",
        "此请求与当前数据冲突。",
        "请求过于频繁。请稍后重试。",
        "服务暂时不可用。请稍后重试。",
        "发生意外错误。请重试。",
    ),
    "ja": (
        "リクエストを処理できませんでした。送信内容を確認してください。",
        "送信された情報の一部が無効です。",
        "この項目は必須です。",
        "この値は無効です。",
        "認証が必要です。もう一度ログインしてください。",
        "有効なサブスクリプションが必要です。",
        "この操作を実行する権限がありません。",
        "要求されたリソースが見つかりません。",
        "このリクエストは現在のデータと競合しています。",
        "リクエストが多すぎます。しばらくしてからもう一度お試しください。",
        "サービスは一時的に利用できません。しばらくしてからもう一度お試しください。",
        "予期しないエラーが発生しました。もう一度お試しください。",
    ),
    "ko": (
        "요청을 처리할 수 없습니다. 제출한 정보를 확인하세요.",
        "제출한 정보 중 일부가 유효하지 않습니다.",
        "필수 입력 항목입니다.",
        "유효하지 않은 값입니다.",
        "인증이 필요합니다. 다시 로그인하세요.",
        "활성 구독이 필요합니다.",
        "이 작업을 수행할 권한이 없습니다.",
        "요청한 리소스를 찾을 수 없습니다.",
        "이 요청이 현재 데이터와 충돌합니다.",
        "요청이 너무 많습니다. 나중에 다시 시도하세요.",
        "서비스를 일시적으로 사용할 수 없습니다. 나중에 다시 시도하세요.",
        "예기치 않은 오류가 발생했습니다. 다시 시도하세요.",
    ),
    "hi": (
        "अनुरोध संसाधित नहीं किया जा सका। भेजी गई जानकारी जाँचें।",
        "भेजी गई कुछ जानकारी अमान्य है।",
        "यह फ़ील्ड आवश्यक है।",
        "यह मान अमान्य है।",
        "प्रमाणीकरण आवश्यक है। कृपया फिर से साइन इन करें।",
        "एक सक्रिय सदस्यता आवश्यक है।",
        "आपको यह कार्रवाई करने की अनुमति नहीं है।",
        "अनुरोधित संसाधन नहीं मिला।",
        "यह अनुरोध मौजूदा डेटा से टकराता है।",
        "बहुत अधिक अनुरोध। कृपया बाद में फिर कोशिश करें।",
        "सेवा अस्थायी रूप से उपलब्ध नहीं है। कृपया बाद में फिर कोशिश करें।",
        "एक अप्रत्याशित त्रुटि हुई। कृपया फिर कोशिश करें।",
    ),
    "bn": (
        "অনুরোধটি প্রক্রিয়া করা যায়নি। পাঠানো তথ্য পরীক্ষা করুন।",
        "পাঠানো কিছু তথ্য অবৈধ।",
        "এই ক্ষেত্রটি আবশ্যক।",
        "এই মানটি অবৈধ।",
        "প্রমাণীকরণ আবশ্যক। আবার সাইন ইন করুন।",
        "একটি সক্রিয় সাবস্ক্রিপশন আবশ্যক।",
        "এই কাজটি করার অনুমতি আপনার নেই।",
        "অনুরোধ করা সংস্থানটি পাওয়া যায়নি।",
        "এই অনুরোধটি বর্তমান তথ্যের সঙ্গে সাংঘর্ষিক।",
        "অনেক বেশি অনুরোধ। পরে আবার চেষ্টা করুন।",
        "পরিষেবাটি সাময়িকভাবে অনুপলব্ধ। পরে আবার চেষ্টা করুন।",
        "একটি অপ্রত্যাশিত ত্রুটি ঘটেছে। আবার চেষ্টা করুন।",
    ),
    "ur": (
        "درخواست پر کارروائی نہیں ہو سکی۔ بھیجی گئی معلومات چیک کریں۔",
        "بھیجی گئی کچھ معلومات درست نہیں ہیں۔",
        "یہ خانہ ضروری ہے۔",
        "یہ قدر درست نہیں ہے۔",
        "توثیق ضروری ہے۔ دوبارہ سائن اِن کریں۔",
        "فعال سبسکرپشن ضروری ہے۔",
        "آپ کو یہ کارروائی کرنے کی اجازت نہیں ہے۔",
        "درخواست کردہ وسیلہ نہیں ملا۔",
        "یہ درخواست موجودہ ڈیٹا سے متصادم ہے۔",
        "بہت زیادہ درخواستیں۔ بعد میں دوبارہ کوشش کریں۔",
        "سروس عارضی طور پر دستیاب نہیں۔ بعد میں دوبارہ کوشش کریں۔",
        "ایک غیر متوقع خرابی پیش آئی۔ دوبارہ کوشش کریں۔",
    ),
    "ta": (
        "கோரிக்கையைச் செயலாக்க முடியவில்லை. சமர்ப்பித்த தகவலைச் சரிபார்க்கவும்.",
        "சமர்ப்பித்த தகவலில் சில தவறானவை.",
        "இந்தப் புலம் கட்டாயம்.",
        "இந்த மதிப்பு தவறானது.",
        "அங்கீகாரம் தேவை. மீண்டும் உள்நுழையவும்.",
        "செயலில் உள்ள சந்தா தேவை.",
        "இந்தச் செயலைச் செய்ய உங்களுக்கு அனுமதி இல்லை.",
        "கோரப்பட்ட வளத்தைக் கண்டறிய முடியவில்லை.",
        "இந்தக் கோரிக்கை தற்போதைய தரவுடன் முரண்படுகிறது.",
        "அதிகமான கோரிக்கைகள். பின்னர் மீண்டும் முயற்சிக்கவும்.",
        "சேவை தற்காலிகமாக கிடைக்கவில்லை. பின்னர் மீண்டும் முயற்சிக்கவும்.",
        "எதிர்பாராத பிழை ஏற்பட்டது. மீண்டும் முயற்சிக்கவும்.",
    ),
    "pa": (
        "ਬੇਨਤੀ ਦੀ ਪ੍ਰਕਿਰਿਆ ਨਹੀਂ ਹੋ ਸਕੀ। ਭੇਜੀ ਜਾਣਕਾਰੀ ਦੀ ਜਾਂਚ ਕਰੋ।",
        "ਭੇਜੀ ਗਈ ਕੁਝ ਜਾਣਕਾਰੀ ਅਵੈਧ ਹੈ।",
        "ਇਹ ਖੇਤਰ ਲਾਜ਼ਮੀ ਹੈ।",
        "ਇਹ ਮੁੱਲ ਅਵੈਧ ਹੈ।",
        "ਪ੍ਰਮਾਣਿਕਤਾ ਲਾਜ਼ਮੀ ਹੈ। ਮੁੜ ਸਾਈਨ ਇਨ ਕਰੋ।",
        "ਇੱਕ ਸਰਗਰਮ ਗਾਹਕੀ ਲਾਜ਼ਮੀ ਹੈ।",
        "ਤੁਹਾਨੂੰ ਇਹ ਕਾਰਵਾਈ ਕਰਨ ਦੀ ਇਜਾਜ਼ਤ ਨਹੀਂ ਹੈ।",
        "ਮੰਗਿਆ ਸਰੋਤ ਨਹੀਂ ਮਿਲਿਆ।",
        "ਇਹ ਬੇਨਤੀ ਮੌਜੂਦਾ ਡਾਟੇ ਨਾਲ ਟਕਰਾਉਂਦੀ ਹੈ।",
        "ਬਹੁਤ ਜ਼ਿਆਦਾ ਬੇਨਤੀਆਂ। ਬਾਅਦ ਵਿੱਚ ਮੁੜ ਕੋਸ਼ਿਸ਼ ਕਰੋ।",
        "ਸੇਵਾ ਅਸਥਾਈ ਤੌਰ 'ਤੇ ਉਪਲਬਧ ਨਹੀਂ ਹੈ। ਬਾਅਦ ਵਿੱਚ ਮੁੜ ਕੋਸ਼ਿਸ਼ ਕਰੋ।",
        "ਇੱਕ ਅਣਕਿਆਸੀ ਗਲਤੀ ਹੋਈ। ਮੁੜ ਕੋਸ਼ਿਸ਼ ਕਰੋ।",
    ),
    "ne": (
        "अनुरोध प्रक्रिया गर्न सकिएन। पठाइएको जानकारी जाँच गर्नुहोस्।",
        "पठाइएको केही जानकारी अमान्य छ।",
        "यो क्षेत्र आवश्यक छ।",
        "यो मान अमान्य छ।",
        "प्रमाणीकरण आवश्यक छ। फेरि साइन इन गर्नुहोस्।",
        "सक्रिय सदस्यता आवश्यक छ।",
        "तपाईंलाई यो कार्य गर्ने अनुमति छैन।",
        "अनुरोध गरिएको स्रोत फेला परेन।",
        "यो अनुरोध हालको डेटासँग बाझिन्छ।",
        "धेरै अनुरोधहरू भए। पछि फेरि प्रयास गर्नुहोस्।",
        "सेवा अस्थायी रूपमा उपलब्ध छैन। पछि फेरि प्रयास गर्नुहोस्।",
        "अप्रत्याशित त्रुटि भयो। फेरि प्रयास गर्नुहोस्।",
    ),
    "vi": (
        "Không thể xử lý yêu cầu. Vui lòng kiểm tra thông tin đã gửi.",
        "Một số thông tin đã gửi không hợp lệ.",
        "Trường này là bắt buộc.",
        "Giá trị này không hợp lệ.",
        "Cần xác thực. Vui lòng đăng nhập lại.",
        "Cần có gói đăng ký đang hoạt động.",
        "Bạn không có quyền thực hiện thao tác này.",
        "Không tìm thấy tài nguyên được yêu cầu.",
        "Yêu cầu này xung đột với dữ liệu hiện tại.",
        "Có quá nhiều yêu cầu. Vui lòng thử lại sau.",
        "Dịch vụ tạm thời không khả dụng. Vui lòng thử lại sau.",
        "Đã xảy ra lỗi không mong muốn. Vui lòng thử lại.",
    ),
    "th": (
        "ไม่สามารถดำเนินการตามคำขอได้ โปรดตรวจสอบข้อมูลที่ส่งมา",
        "ข้อมูลที่ส่งมาบางส่วนไม่ถูกต้อง",
        "จำเป็นต้องกรอกข้อมูลในช่องนี้",
        "ค่านี้ไม่ถูกต้อง",
        "ต้องยืนยันตัวตน โปรดลงชื่อเข้าใช้อีกครั้ง",
        "ต้องมีการสมัครสมาชิกที่ใช้งานอยู่",
        "คุณไม่มีสิทธิ์ดำเนินการนี้",
        "ไม่พบทรัพยากรที่ร้องขอ",
        "คำขอนี้ขัดแย้งกับข้อมูลปัจจุบัน",
        "มีคำขอมากเกินไป โปรดลองอีกครั้งภายหลัง",
        "บริการไม่พร้อมใช้งานชั่วคราว โปรดลองอีกครั้งภายหลัง",
        "เกิดข้อผิดพลาดที่ไม่คาดคิด โปรดลองอีกครั้ง",
    ),
    "id": (
        "Permintaan tidak dapat diproses. Periksa informasi yang dikirim.",
        "Beberapa informasi yang dikirim tidak valid.",
        "Kolom ini wajib diisi.",
        "Nilai ini tidak valid.",
        "Autentikasi diperlukan. Silakan masuk kembali.",
        "Langganan aktif diperlukan.",
        "Anda tidak memiliki izin untuk melakukan tindakan ini.",
        "Sumber daya yang diminta tidak ditemukan.",
        "Permintaan ini bertentangan dengan data saat ini.",
        "Terlalu banyak permintaan. Coba lagi nanti.",
        "Layanan sementara tidak tersedia. Coba lagi nanti.",
        "Terjadi kesalahan yang tidak terduga. Coba lagi.",
    ),
    "ms": (
        "Permintaan tidak dapat diproses. Semak maklumat yang dihantar.",
        "Sesetengah maklumat yang dihantar tidak sah.",
        "Medan ini wajib diisi.",
        "Nilai ini tidak sah.",
        "Pengesahan diperlukan. Sila log masuk semula.",
        "Langganan aktif diperlukan.",
        "Anda tidak dibenarkan melakukan tindakan ini.",
        "Sumber yang diminta tidak ditemui.",
        "Permintaan ini bercanggah dengan data semasa.",
        "Terlalu banyak permintaan. Cuba lagi kemudian.",
        "Perkhidmatan tidak tersedia buat sementara waktu. Cuba lagi kemudian.",
        "Ralat yang tidak dijangka berlaku. Cuba lagi.",
    ),
    "tl": (
        "Hindi maproseso ang kahilingan. Suriin ang impormasyong ipinadala.",
        "May ilang impormasyong ipinadala na hindi wasto.",
        "Kinakailangan ang field na ito.",
        "Hindi wasto ang value na ito.",
        "Kailangan ng pagpapatunay. Mag-sign in muli.",
        "Kailangan ng aktibong subscription.",
        "Wala kang pahintulot na gawin ang pagkilos na ito.",
        "Hindi nakita ang hiniling na resource.",
        "Sumasalungat ang kahilingang ito sa kasalukuyang data.",
        "Napakaraming kahilingan. Subukan muli mamaya.",
        "Pansamantalang hindi available ang serbisyo. Subukan muli mamaya.",
        "May hindi inaasahang error. Subukan muli.",
    ),
    "my": (
        "တောင်းဆိုချက်ကို လုပ်ဆောင်၍မရပါ။ ပေးပို့ထားသော အချက်အလက်ကို စစ်ဆေးပါ။",
        "ပေးပို့ထားသော အချက်အလက်အချို့ မမှန်ကန်ပါ။",
        "ဤအကွက်ကို ဖြည့်ရန် လိုအပ်သည်။",
        "ဤတန်ဖိုး မမှန်ကန်ပါ။",
        "အထောက်အထားပြရန် လိုအပ်သည်။ ထပ်မံဝင်ရောက်ပါ။",
        "အသုံးပြုနေသော စာရင်းသွင်းမှု လိုအပ်သည်။",
        "ဤလုပ်ဆောင်ချက်ကို လုပ်ဆောင်ရန် ခွင့်ပြုချက်မရှိပါ။",
        "တောင်းဆိုထားသော အရင်းအမြစ်ကို မတွေ့ပါ။",
        "ဤတောင်းဆိုချက်သည် လက်ရှိဒေတာနှင့် ကွဲလွဲနေသည်။",
        "တောင်းဆိုမှုများလွန်းနေသည်။ နောက်မှ ထပ်ကြိုးစားပါ။",
        "ဝန်ဆောင်မှုကို ယာယီအသုံးမပြုနိုင်ပါ။ နောက်မှ ထပ်ကြိုးစားပါ။",
        "မမျှော်လင့်ထားသော အမှားတစ်ခု ဖြစ်ပွားခဲ့သည်။ ထပ်ကြိုးစားပါ။",
    ),
    "km": (
        "មិនអាចដំណើរការសំណើបានទេ។ សូមពិនិត្យព័ត៌មានដែលបានផ្ញើ។",
        "ព័ត៌មានដែលបានផ្ញើមួយចំនួនមិនត្រឹមត្រូវទេ។",
        "ត្រូវបំពេញវាលនេះ។",
        "តម្លៃនេះមិនត្រឹមត្រូវទេ។",
        "ត្រូវការការផ្ទៀងផ្ទាត់។ សូមចូលគណនីម្ដងទៀត។",
        "ត្រូវការការជាវដែលកំពុងសកម្ម។",
        "អ្នកមិនមានសិទ្ធិធ្វើសកម្មភាពនេះទេ។",
        "រកមិនឃើញធនធានដែលបានស្នើទេ។",
        "សំណើនេះមានជម្លោះជាមួយទិន្នន័យបច្ចុប្បន្ន។",
        "មានសំណើច្រើនពេក។ សូមព្យាយាមម្ដងទៀតនៅពេលក្រោយ។",
        "សេវាកម្មមិនអាចប្រើបានជាបណ្ដោះអាសន្នទេ។ សូមព្យាយាមម្ដងទៀតពេលក្រោយ។",
        "មានកំហុសមិនបានរំពឹងទុក។ សូមព្យាយាមម្ដងទៀត។",
    ),
    "mn": (
        "Хүсэлтийг боловсруулах боломжгүй. Илгээсэн мэдээллээ шалгана уу.",
        "Илгээсэн мэдээллийн зарим нь буруу байна.",
        "Энэ талбарыг заавал бөглөнө.",
        "Энэ утга буруу байна.",
        "Нэвтрэлт шаардлагатай. Дахин нэвтэрнэ үү.",
        "Идэвхтэй захиалга шаардлагатай.",
        "Та энэ үйлдлийг хийх эрхгүй байна.",
        "Хүссэн нөөц олдсонгүй.",
        "Энэ хүсэлт одоогийн өгөгдөлтэй зөрчилдөж байна.",
        "Хэт олон хүсэлт байна. Дараа дахин оролдоно уу.",
        "Үйлчилгээ түр боломжгүй байна. Дараа дахин оролдоно уу.",
        "Санаандгүй алдаа гарлаа. Дахин оролдоно уу.",
    ),
}

_LOCALE_LANGUAGE_ALIASES = {
    "fr-CA": "fr",
    "fr-FR": "fr",
    "en-GB": "en",
    "ar-EG": "ar",
}

_AUTH_MESSAGES_BY_LANGUAGE: dict[str, tuple[str, str]] = {
    "en": ("Your email address is not verified. Check your inbox.", "Email or password is incorrect."),
    "fr": ("Adresse e-mail non vérifiée. Vérifiez votre boîte de réception.", "Adresse e-mail ou mot de passe incorrect."),
    "es": ("Tu correo electrónico no está verificado. Revisa tu bandeja de entrada.", "El correo electrónico o la contraseña no son correctos."),
    "pt": ("O endereço de e-mail não foi verificado. Verifique a sua caixa de entrada.", "O e-mail ou a palavra-passe estão incorretos."),
    "ro": ("Adresa de e-mail nu este verificată. Verificați căsuța de e-mail.", "Adresa de e-mail sau parola este incorectă."),
    "de": ("Ihre E-Mail-Adresse ist nicht bestätigt. Prüfen Sie Ihren Posteingang.", "E-Mail-Adresse oder Passwort ist falsch."),
    "it": ("L’indirizzo e-mail non è verificato. Controlla la posta in arrivo.", "L’indirizzo e-mail o la password non sono corretti."),
    "nl": ("Uw e-mailadres is niet bevestigd. Controleer uw inbox.", "Het e-mailadres of wachtwoord is onjuist."),
    "pl": ("Adres e-mail nie został zweryfikowany. Sprawdź swoją skrzynkę odbiorczą.", "Adres e-mail lub hasło są nieprawidłowe."),
    "ru": ("Адрес электронной почты не подтверждён. Проверьте входящие сообщения.", "Неверный адрес электронной почты или пароль."),
    "uk": ("Електронну адресу не підтверджено. Перевірте вхідні повідомлення.", "Неправильна електронна адреса або пароль."),
    "el": ("Η διεύθυνση email δεν έχει επαληθευτεί. Ελέγξτε τα εισερχόμενά σας.", "Το email ή ο κωδικός πρόσβασης δεν είναι σωστά."),
    "sv": ("E-postadressen har inte verifierats. Kontrollera din inkorg.", "E-postadressen eller lösenordet är felaktigt."),
    "tr": ("E-posta adresiniz doğrulanmadı. Gelen kutunuzu kontrol edin.", "E-posta adresi veya parola hatalı."),
    "cs": ("E-mailová adresa není ověřena. Zkontrolujte svou doručenou poštu.", "E-mailová adresa nebo heslo jsou nesprávné."),
    "ka": ("ელფოსტის მისამართი დადასტურებული არ არის. შეამოწმეთ შემოსული წერილები.", "ელფოსტის მისამართი ან პაროლი არასწორია."),
    "hy": ("Էլեկտրոնային հասցեն հաստատված չէ։ Ստուգեք մուտքային նամակները։", "Էլեկտրոնային հասցեն կամ գաղտնաբառը սխալ է։"),
    "ar": ("لم يتم التحقق من عنوان بريدك الإلكتروني. تحقق من صندوق الوارد.", "البريد الإلكتروني أو كلمة المرور غير صحيحة."),
    "he": ("כתובת הדוא״ל לא אומתה. יש לבדוק את תיבת הדואר הנכנס.", "כתובת הדוא״ל או הסיסמה שגויות."),
    "fa": ("نشانی ایمیل شما تأیید نشده است. صندوق ورودی را بررسی کنید.", "ایمیل یا گذرواژه نادرست است."),
    "sw": ("Anwani yako ya barua pepe haijathibitishwa. Angalia kikasha chako.", "Barua pepe au nenosiri si sahihi."),
    "am": ("የኢሜይል አድራሻዎ አልተረጋገጠም። የገቢ መልዕክት ሳጥንዎን ይመልከቱ።", "ኢሜይሉ ወይም የይለፍ ቃሉ ትክክል አይደለም።"),
    "af": ("Jou e-posadres is nie geverifieer nie. Gaan jou inkassie na.", "Die e-posadres of wagwoord is verkeerd."),
    "ha": ("Ba a tabbatar da adireshin imel ɗinka ba. Duba akwatin saƙonka.", "Imel ko kalmar sirri ba daidai ba ce."),
    "zh": ("您的电子邮箱尚未验证。请检查收件箱。", "电子邮箱或密码不正确。"),
    "ja": ("メールアドレスが確認されていません。受信トレイを確認してください。", "メールアドレスまたはパスワードが正しくありません。"),
    "ko": ("이메일 주소가 확인되지 않았습니다. 받은 편지함을 확인하세요.", "이메일 또는 비밀번호가 올바르지 않습니다."),
    "hi": ("आपका ईमेल पता सत्यापित नहीं है। अपना इनबॉक्स जाँचें।", "ईमेल या पासवर्ड गलत है।"),
    "bn": ("আপনার ইমেল ঠিকানা যাচাই করা হয়নি। ইনবক্স দেখুন।", "ইমেল বা পাসওয়ার্ড সঠিক নয়।"),
    "ur": ("آپ کے ای میل پتے کی تصدیق نہیں ہوئی۔ اپنا اِن باکس دیکھیں۔", "ای میل یا پاس ورڈ درست نہیں ہے۔"),
    "ta": ("உங்கள் மின்னஞ்சல் முகவரி சரிபார்க்கப்படவில்லை. இன்பாக்ஸைப் பார்க்கவும்.", "மின்னஞ்சல் அல்லது கடவுச்சொல் தவறானது."),
    "pa": ("ਤੁਹਾਡਾ ਈਮੇਲ ਪਤਾ ਤਸਦੀਕ ਨਹੀਂ ਹੋਇਆ। ਆਪਣਾ ਇਨਬਾਕਸ ਵੇਖੋ।", "ਈਮੇਲ ਜਾਂ ਪਾਸਵਰਡ ਗਲਤ ਹੈ।"),
    "ne": ("तपाईंको इमेल ठेगाना प्रमाणित भएको छैन। इनबक्स जाँच गर्नुहोस्।", "इमेल वा पासवर्ड गलत छ।"),
    "vi": ("Địa chỉ email chưa được xác minh. Vui lòng kiểm tra hộp thư đến.", "Email hoặc mật khẩu không chính xác."),
    "th": ("ยังไม่ได้ยืนยันที่อยู่อีเมล โปรดตรวจสอบกล่องจดหมายเข้า", "อีเมลหรือรหัสผ่านไม่ถูกต้อง"),
    "id": ("Alamat email Anda belum diverifikasi. Periksa kotak masuk Anda.", "Email atau kata sandi salah."),
    "ms": ("Alamat e-mel anda belum disahkan. Semak peti masuk anda.", "Alamat e-mel atau kata laluan tidak betul."),
    "tl": ("Hindi pa nabe-verify ang iyong email address. Tingnan ang inbox mo.", "Mali ang email o password."),
    "my": ("သင့်အီးမေးလ်လိပ်စာကို အတည်မပြုရသေးပါ။ Inbox ကိုစစ်ဆေးပါ။", "အီးမေးလ် သို့မဟုတ် စကားဝှက် မှားနေသည်။"),
    "km": ("អាសយដ្ឋានអ៊ីមែលរបស់អ្នកមិនទាន់បានផ្ទៀងផ្ទាត់ទេ។ សូមពិនិត្យប្រអប់សំបុត្រ។", "អ៊ីមែល ឬពាក្យសម្ងាត់មិនត្រឹមត្រូវទេ។"),
    "mn": ("Таны имэйл хаяг баталгаажаагүй байна. Ирсэн имэйлээ шалгана уу.", "Имэйл хаяг эсвэл нууц үг буруу байна."),
}

_PRICE_UNIT_REQUIRED_BY_LANGUAGE = {
    "en": "Price analysis requires a unit price.",
    "fr": "L’analyse des prix nécessite un prix unitaire.",
    "es": "El análisis de precios requiere un precio unitario.",
    "pt": "A análise de preços requer um preço unitário.",
    "ro": "Analiza prețurilor necesită un preț unitar.",
    "de": "Für die Preisanalyse ist ein Stückpreis erforderlich.",
    "it": "L’analisi dei prezzi richiede un prezzo unitario.",
    "nl": "Voor prijsanalyse is een eenheidsprijs vereist.",
    "pl": "Analiza cen wymaga podania ceny jednostkowej.",
    "ru": "Для анализа цен необходимо указать цену за единицу.",
    "uk": "Для аналізу цін потрібно вказати ціну за одиницю.",
    "el": "Για την ανάλυση τιμών απαιτείται τιμή μονάδας.",
    "sv": "Prisanalys kräver ett styckepris.",
    "tr": "Fiyat analizi için birim fiyat gereklidir.",
    "cs": "Analýza cen vyžaduje jednotkovou cenu.",
    "ka": "ფასის ანალიზისთვის საჭიროა ერთეულის ფასი.",
    "hy": "Գների վերլուծության համար անհրաժեշտ է միավորի գին։",
    "ar": "يتطلب تحليل الأسعار تحديد سعر الوحدة.",
    "he": "ניתוח מחירים מחייב ציון מחיר ליחידה.",
    "fa": "تحلیل قیمت به قیمت واحد نیاز دارد.",
    "sw": "Uchambuzi wa bei unahitaji bei ya kila kipande.",
    "am": "የዋጋ ትንተና የአንድ ክፍል ዋጋ ይፈልጋል።",
    "af": "Pryse-ontleding vereis ’n eenheidsprys.",
    "ha": "Binciken farashi yana buƙatar farashin kowane guda.",
    "zh": "价格分析需要提供单价。",
    "ja": "価格分析には単価が必要です。",
    "ko": "가격 분석에는 단가가 필요합니다.",
    "hi": "मूल्य विश्लेषण के लिए प्रति इकाई मूल्य आवश्यक है।",
    "bn": "মূল্য বিশ্লেষণের জন্য একক মূল্য প্রয়োজন।",
    "ur": "قیمت کے تجزیے کے لیے فی یونٹ قیمت درکار ہے۔",
    "ta": "விலை பகுப்பாய்விற்கு அலகு விலை தேவை.",
    "pa": "ਕੀਮਤ ਦੇ ਵਿਸ਼ਲੇਸ਼ਣ ਲਈ ਇਕਾਈ ਕੀਮਤ ਲੋੜੀਂਦੀ ਹੈ।",
    "ne": "मूल्य विश्लेषणका लागि प्रति एकाइ मूल्य आवश्यक छ।",
    "vi": "Phân tích giá cần có đơn giá.",
    "th": "การวิเคราะห์ราคาต้องระบุราคาต่อหน่วย",
    "id": "Analisis harga memerlukan harga satuan.",
    "ms": "Analisis harga memerlukan harga seunit.",
    "tl": "Kailangan ng presyo kada yunit para sa pagsusuri ng presyo.",
    "my": "စျေးနှုန်းခွဲခြမ်းစိတ်ဖြာရန် တစ်ယူနစ်စျေးနှုန်း လိုအပ်သည်။",
    "km": "ការវិភាគតម្លៃត្រូវការតម្លៃក្នុងមួយឯកតា។",
    "mn": "Үнийн шинжилгээнд нэгжийн үнэ шаардлагатай.",
}

_API_SUCCESS_MESSAGES_BY_LANGUAGE = {
    "en": ("You have been signed out.", "Your enterprise quote request was received. Our team will contact you within one business day."),
    "fr": ("Votre session est fermée.", "Votre demande de devis Enterprise a été reçue. Notre équipe vous contactera sous un jour ouvré."),
    "es": ("Has cerrado la sesión.", "Hemos recibido tu solicitud de presupuesto Enterprise. Nuestro equipo se pondrá en contacto contigo en un día laborable."),
    "pt": ("A sua sessão foi terminada.", "Recebemos o seu pedido de orçamento Enterprise. A nossa equipa entrará em contacto consigo no prazo de um dia útil."),
    "ro": ("Sesiunea a fost închisă.", "Solicitarea de ofertă Enterprise a fost primită. Echipa noastră vă va contacta într-o zi lucrătoare."),
    "de": ("Sie wurden abgemeldet.", "Ihre Enterprise-Angebotsanfrage ist eingegangen. Unser Team meldet sich innerhalb eines Werktags bei Ihnen."),
    "it": ("Hai terminato la sessione.", "La richiesta di preventivo Enterprise è stata ricevuta. Il nostro team ti contatterà entro un giorno lavorativo."),
    "nl": ("U bent afgemeld.", "Uw aanvraag voor een Enterprise-offerte is ontvangen. Ons team neemt binnen één werkdag contact met u op."),
    "pl": ("Wylogowano.", "Otrzymaliśmy prośbę o ofertę Enterprise. Nasz zespół skontaktuje się z Tobą w ciągu jednego dnia roboczego."),
    "ru": ("Вы вышли из системы.", "Запрос предложения Enterprise получен. Наша команда свяжется с вами в течение одного рабочего дня."),
    "uk": ("Ви вийшли із системи.", "Запит пропозиції Enterprise отримано. Наша команда зв’яжеться з вами протягом одного робочого дня."),
    "el": ("Αποσυνδεθήκατε.", "Λάβαμε το αίτημά σας για προσφορά Enterprise. Η ομάδα μας θα επικοινωνήσει μαζί σας εντός μίας εργάσιμης ημέρας."),
    "sv": ("Du har loggat ut.", "Vi har tagit emot din offertförfrågan för Enterprise. Vårt team kontaktar dig inom en arbetsdag."),
    "tr": ("Oturumunuz kapatıldı.", "Enterprise fiyat teklifi talebiniz alındı. Ekibimiz bir iş günü içinde sizinle iletişime geçecektir."),
    "cs": ("Byli jste odhlášeni.", "Žádost o nabídku Enterprise jsme obdrželi. Náš tým vás kontaktuje do jednoho pracovního dne."),
    "ka": ("სესიიდან გამოხვედით.", "Enterprise შეთავაზების მოთხოვნა მიღებულია. ჩვენი გუნდი ერთ სამუშაო დღეში დაგიკავშირდებათ."),
    "hy": ("Դուք դուրս եք եկել։", "Enterprise առաջարկի հարցումն ստացվել է։ Մեր թիմը կապ կհաստատի մեկ աշխատանքային օրվա ընթացքում։"),
    "ar": ("تم تسجيل خروجك.", "تم استلام طلب عرض Enterprise. سيتواصل معك فريقنا خلال يوم عمل واحد."),
    "he": ("יצאת מהחשבון.", "בקשת הצעת המחיר ל-Enterprise התקבלה. הצוות שלנו ייצור איתך קשר בתוך יום עסקים אחד."),
    "fa": ("از حساب خارج شدید.", "درخواست پیشنهاد Enterprise دریافت شد. تیم ما ظرف یک روز کاری با شما تماس می‌گیرد."),
    "sw": ("Umetoka kwenye akaunti.", "Ombi lako la bei ya Enterprise limepokelewa. Timu yetu itawasiliana nawe ndani ya siku moja ya kazi."),
    "am": ("ከመለያዎ ወጥተዋል።", "የEnterprise የዋጋ ጥያቄዎ ደርሶናል። ቡድናችን በአንድ የሥራ ቀን ውስጥ ያነጋግርዎታል።"),
    "af": ("Jy is afgemeld.", "Jou Enterprise-kwotasieversoek is ontvang. Ons span sal jou binne een werksdag kontak."),
    "ha": ("An fita daga asusunka.", "Mun karɓi buƙatar farashin Enterprise. Ƙungiyarmu za ta tuntube ka cikin ranar aiki ɗaya."),
    "zh": ("你已退出登录。", "已收到你的 Enterprise 报价申请。我们的团队会在一个工作日内与你联系。"),
    "ja": ("ログアウトしました。", "Enterprise の見積もり依頼を受け付けました。1 営業日以内に担当チームからご連絡します。"),
    "ko": ("로그아웃되었습니다.", "Enterprise 견적 요청이 접수되었습니다. 영업일 기준 하루 이내에 담당자가 연락드리겠습니다."),
    "hi": ("आप साइन आउट हो गए हैं।", "आपका Enterprise कोटेशन अनुरोध मिल गया है। हमारी टीम एक कार्यदिवस के भीतर आपसे संपर्क करेगी।"),
    "bn": ("আপনি সাইন আউট করেছেন।", "আপনার Enterprise মূল্য-প্রস্তাবের অনুরোধ পেয়েছি। আমাদের দল এক কর্মদিবসের মধ্যে যোগাযোগ করবে।"),
    "ur": ("آپ سائن آؤٹ ہو گئے ہیں۔", "آپ کی Enterprise قیمت کی درخواست موصول ہو گئی ہے۔ ہماری ٹیم ایک کاروباری دن میں آپ سے رابطہ کرے گی۔"),
    "ta": ("நீங்கள் வெளியேறிவிட்டீர்கள்.", "Enterprise விலைப்புள்ளி கோரிக்கை கிடைத்தது. ஒரு வேலை நாளுக்குள் எங்கள் குழு உங்களைத் தொடர்புகொள்ளும்."),
    "pa": ("ਤੁਸੀਂ ਸਾਈਨ ਆਉਟ ਕਰ ਦਿੱਤਾ ਹੈ।", "ਤੁਹਾਡੀ Enterprise ਕੀਮਤ ਦੀ ਬੇਨਤੀ ਮਿਲ ਗਈ ਹੈ। ਸਾਡੀ ਟੀਮ ਇੱਕ ਕਾਰੋਬਾਰੀ ਦਿਨ ਵਿੱਚ ਤੁਹਾਡੇ ਨਾਲ ਸੰਪਰਕ ਕਰੇਗੀ।"),
    "ne": ("तपाईं साइन आउट हुनुभयो।", "तपाईंको Enterprise मूल्य प्रस्ताव अनुरोध प्राप्त भयो। हाम्रो टोलीले एक कार्यदिनभित्र सम्पर्क गर्नेछ।"),
    "vi": ("Bạn đã đăng xuất.", "Chúng tôi đã nhận yêu cầu báo giá Enterprise. Nhóm sẽ liên hệ với bạn trong một ngày làm việc."),
    "th": ("คุณออกจากระบบแล้ว", "ได้รับคำขอใบเสนอราคา Enterprise แล้ว ทีมงานจะติดต่อกลับภายในหนึ่งวันทำการ"),
    "id": ("Anda telah keluar.", "Permintaan penawaran Enterprise Anda telah diterima. Tim kami akan menghubungi Anda dalam satu hari kerja."),
    "ms": ("Anda telah log keluar.", "Permintaan sebut harga Enterprise anda telah diterima. Pasukan kami akan menghubungi anda dalam satu hari bekerja."),
    "tl": ("Naka-sign out ka na.", "Natanggap na ang kahilingan mo para sa quote ng Enterprise. Makikipag-ugnayan ang aming team sa loob ng isang araw ng trabaho."),
    "my": ("အကောင့်မှ ထွက်ပြီးပါပြီ။", "Enterprise ဈေးနှုန်းတောင်းဆိုချက်ကို လက်ခံရရှိပါပြီ။ အလုပ်လုပ်ရက်တစ်ရက်အတွင်း ကျွန်ုပ်တို့အဖွဲ့က ဆက်သွယ်ပါမည်။"),
    "km": ("អ្នកបានចាកចេញពីគណនីហើយ។", "យើងបានទទួលសំណើសុំតម្លៃ Enterprise របស់អ្នកហើយ។ ក្រុមការងារនឹងទាក់ទងអ្នកក្នុងរយៈពេលមួយថ្ងៃធ្វើការ។"),
    "mn": ("Та системээс гарлаа.", "Enterprise үнийн саналын хүсэлтийг хүлээн авлаа. Манай баг ажлын нэг өдрийн дотор холбогдоно."),
}

_DATASET_SOURCE_UNAVAILABLE_BY_LANGUAGE = {
    "en": "The original dataset file is no longer available in storage. Reimport it to restore the cleaned data.",
    "fr": "Le fichier original de ce dataset n'est plus disponible sur le stockage. Réimportez-le pour restaurer les données nettoyées.",
    "es": "El archivo original del conjunto de datos ya no está disponible en el almacenamiento. Vuelve a importarlo para restaurar los datos procesados.",
    "pt": "O ficheiro original do conjunto de dados já não está disponível no armazenamento. Volte a importá-lo para restaurar os dados tratados.",
    "ro": "Fișierul original al setului de date nu mai este disponibil în stocare. Importați-l din nou pentru a restaura datele procesate.",
    "de": "Die Originaldatei des Datasets ist nicht mehr im Speicher verfügbar. Importieren Sie sie erneut, um die bereinigten Daten wiederherzustellen.",
    "it": "Il file originale del dataset non è più disponibile nell'archivio. Importalo di nuovo per ripristinare i dati elaborati.",
    "nl": "Het oorspronkelijke datasetbestand is niet meer beschikbaar in de opslag. Importeer het opnieuw om de verwerkte gegevens te herstellen.",
    "pl": "Oryginalny plik zbioru danych nie jest już dostępny w pamięci. Zaimportuj go ponownie, aby przywrócić przetworzone dane.",
    "ru": "Исходный файл набора данных больше недоступен в хранилище. Импортируйте его повторно, чтобы восстановить обработанные данные.",
    "uk": "Вихідний файл набору даних більше недоступний у сховищі. Імпортуйте його знову, щоб відновити оброблені дані.",
    "el": "Το αρχικό αρχείο του συνόλου δεδομένων δεν είναι πλέον διαθέσιμο στον χώρο αποθήκευσης. Εισαγάγετέ το ξανά για να επαναφέρετε τα επεξεργασμένα δεδομένα.",
    "sv": "Den ursprungliga datauppsättningsfilen finns inte längre i lagringen. Importera den igen för att återställa de bearbetade uppgifterna.",
    "tr": "Veri kümesinin özgün dosyası artık depolama alanında bulunmuyor. İşlenen verileri geri yüklemek için dosyayı yeniden içe aktarın.",
    "cs": "Původní soubor datové sady již není v úložišti dostupný. Znovu jej naimportujte a obnovte zpracovaná data.",
    "ka": "მონაცემთა ნაკრების საწყისი ფაილი საცავში აღარ არის ხელმისაწვდომი. დამუშავებული მონაცემების აღსადგენად ხელახლა შემოიტანეთ ფაილი.",
    "hy": "Տվյալների հավաքածուի սկզբնական ֆայլն այլևս հասանելի չէ պահոցում։ Մշակված տվյալները վերականգնելու համար կրկին ներմուծեք այն։",
    "ar": "لم يعد الملف الأصلي لمجموعة البيانات متاحًا في مساحة التخزين. أعد استيراده لاستعادة البيانات المعالجة.",
    "he": "קובץ המקור של מערך הנתונים אינו זמין עוד באחסון. יש לייבא אותו מחדש כדי לשחזר את הנתונים המעובדים.",
    "fa": "فایل اصلی مجموعه‌داده دیگر در فضای ذخیره‌سازی موجود نیست. برای بازیابی داده‌های پردازش‌شده، آن را دوباره وارد کنید.",
    "sw": "Faili asili ya mkusanyiko wa data haipatikani tena kwenye hifadhi. Iingize tena ili kurejesha data iliyochakatwa.",
    "am": "የውሂብ ስብስቡ ዋና ፋይል በማከማቻው ውስጥ ከእንግዲህ አይገኝም። የተሰራውን ውሂብ ለመመለስ እንደገና ያስገቡት።",
    "af": "Die oorspronklike datastellingslêer is nie meer in die berging beskikbaar nie. Voer dit weer in om die verwerkte data te herstel.",
    "ha": "Fayil ɗin asali na rukunin bayanan ba ya cikin ma’ajiya yanzu. Sake shigar da shi don dawo da bayanan da aka sarrafa.",
    "zh": "数据集的原始文件已不在存储中。请重新导入以恢复已处理的数据。",
    "ja": "データセットの元ファイルはストレージにありません。処理済みデータを復元するには、ファイルを再インポートしてください。",
    "ko": "데이터 세트의 원본 파일을 저장소에서 찾을 수 없습니다. 처리된 데이터를 복원하려면 다시 가져오세요.",
    "hi": "डेटासेट की मूल फ़ाइल अब स्टोरेज में उपलब्ध नहीं है। संसाधित डेटा बहाल करने के लिए इसे फिर से आयात करें।",
    "bn": "ডেটাসেটের মূল ফাইলটি আর স্টোরেজে নেই। প্রক্রিয়াকৃত ডেটা পুনরুদ্ধার করতে এটি আবার ইমপোর্ট করুন।",
    "ur": "ڈیٹاسیٹ کی اصل فائل اب اسٹوریج میں دستیاب نہیں ہے۔ پراسیس شدہ ڈیٹا بحال کرنے کے لیے اسے دوبارہ درآمد کریں۔",
    "ta": "தரவுத்தொகுப்பின் அசல் கோப்பு சேமிப்பகத்தில் இல்லை. செயலாக்கப்பட்ட தரவை மீட்டெடுக்க அதை மீண்டும் இறக்குமதி செய்யவும்.",
    "pa": "ਡਾਟਾਸੈੱਟ ਦੀ ਅਸਲ ਫ਼ਾਈਲ ਹੁਣ ਸਟੋਰੇਜ ਵਿੱਚ ਉਪਲਬਧ ਨਹੀਂ ਹੈ। ਪ੍ਰੋਸੈਸ ਕੀਤਾ ਡਾਟਾ ਵਾਪਸ ਲਿਆਉਣ ਲਈ ਇਸਨੂੰ ਮੁੜ ਇੰਪੋਰਟ ਕਰੋ।",
    "ne": "डेटासेटको मूल फाइल अब भण्डारणमा उपलब्ध छैन। प्रशोधित डेटा पुनर्स्थापना गर्न यसलाई पुनः आयात गर्नुहोस्।",
    "vi": "Tệp gốc của tập dữ liệu không còn trong kho lưu trữ. Hãy nhập lại để khôi phục dữ liệu đã xử lý.",
    "th": "ไม่มีไฟล์ต้นฉบับของชุดข้อมูลในพื้นที่จัดเก็บแล้ว โปรดนำเข้าอีกครั้งเพื่อกู้คืนข้อมูลที่ประมวลผลแล้ว",
    "id": "File asli kumpulan data sudah tidak tersedia di penyimpanan. Impor ulang untuk memulihkan data yang telah diproses.",
    "ms": "Fail asal set data tiada lagi dalam storan. Import semula untuk memulihkan data yang telah diproses.",
    "tl": "Wala na sa storage ang orihinal na file ng dataset. I-import itong muli upang maibalik ang naprosesong data.",
    "my": "ဒေတာအစု၏ မူရင်းဖိုင်ကို သိုလှောင်မှုတွင် မရရှိနိုင်တော့ပါ။ ပြုပြင်ထားသောဒေတာကို ပြန်ရယူရန် ထပ်မံတင်သွင်းပါ။",
    "km": "ឯកសារដើមរបស់សំណុំទិន្នន័យមិនមានក្នុងកន្លែងផ្ទុកទៀតទេ។ សូមនាំចូលម្ដងទៀត ដើម្បីស្ដារទិន្នន័យដែលបានដំណើរការ។",
    "mn": "Өгөгдлийн багцын эх файл хадгалах санд байхгүй байна. Боловсруулсан өгөгдлийг сэргээхийн тулд дахин импортлоно уу.",
}

_MODULE_UNAVAILABLE_BY_LANGUAGE = {
    "en": "This module is not available yet.",
    "fr": "Ce module n’est pas encore disponible.",
    "es": "Este módulo aún no está disponible.",
    "pt": "Este módulo ainda não está disponível.",
    "ro": "Acest modul nu este încă disponibil.",
    "de": "Dieses Modul ist noch nicht verfügbar.",
    "it": "Questo modulo non è ancora disponibile.",
    "nl": "Deze module is nog niet beschikbaar.",
    "pl": "Ten moduł nie jest jeszcze dostępny.",
    "ru": "Этот модуль пока недоступен.",
    "uk": "Цей модуль поки недоступний.",
    "el": "Αυτή η ενότητα δεν είναι ακόμη διαθέσιμη.",
    "sv": "Den här modulen är inte tillgänglig ännu.",
    "tr": "Bu modül henüz kullanılamıyor.",
    "cs": "Tento modul zatím není k dispozici.",
    "ka": "ეს მოდული ჯერ ხელმისაწვდომი არ არის.",
    "hy": "Այս մոդուլը դեռ հասանելի չէ։",
    "ar": "هذه الوحدة غير متاحة بعد.",
    "he": "המודול הזה עדיין אינו זמין.",
    "fa": "این ماژول هنوز در دسترس نیست.",
    "sw": "Moduli hii bado haipatikani.",
    "am": "ይህ ሞጁል ገና አይገኝም።",
    "af": "Hierdie module is nog nie beskikbaar nie.",
    "ha": "Wannan manhaja ba ta samuwa tukuna.",
    "zh": "此模块暂不可用。",
    "ja": "このモジュールはまだ利用できません。",
    "ko": "이 모듈은 아직 사용할 수 없습니다.",
    "hi": "यह मॉड्यूल अभी उपलब्ध नहीं है।",
    "bn": "এই মডিউলটি এখনও উপলভ্য নয়।",
    "ur": "یہ ماڈیول ابھی دستیاب نہیں ہے۔",
    "ta": "இந்தத் தொகுதி இன்னும் கிடைக்கவில்லை.",
    "pa": "ਇਹ ਮੋਡੀਊਲ ਹਾਲੇ ਉਪਲਬਧ ਨਹੀਂ ਹੈ।",
    "ne": "यो मोड्युल अहिले उपलब्ध छैन।",
    "vi": "Mô-đun này hiện chưa khả dụng.",
    "th": "โมดูลนี้ยังไม่พร้อมใช้งาน",
    "id": "Modul ini belum tersedia.",
    "ms": "Modul ini belum tersedia.",
    "tl": "Hindi pa available ang module na ito.",
    "my": "ဤမော်ဂျူးကို မရရှိနိုင်သေးပါ။",
    "km": "ម៉ូឌុលនេះមិនទាន់មាននៅឡើយទេ។",
    "mn": "Энэ модуль хараахан боломжгүй байна.",
}

ERROR_MESSAGES: dict[str, dict[str, str]] = {}
for locale_info in LOCALES:
    language = _LOCALE_LANGUAGE_ALIASES.get(locale_info.locale, locale_info.locale)
    values = _MESSAGES_BY_LANGUAGE[language]
    if len(values) != len(_MESSAGE_KEYS):
        raise RuntimeError(f"Incomplete API error catalog for locale {locale_info.locale}")
    ERROR_MESSAGES[locale_info.locale] = dict(zip(_MESSAGE_KEYS, values, strict=True))

for locale_info in LOCALES:
    language = _LOCALE_LANGUAGE_ALIASES.get(locale_info.locale, locale_info.locale)
    email_verification, invalid_credentials = _AUTH_MESSAGES_BY_LANGUAGE[language]
    ERROR_MESSAGES[locale_info.locale]["email_verification_required"] = email_verification
    ERROR_MESSAGES[locale_info.locale]["invalid_credentials"] = invalid_credentials
    ERROR_MESSAGES[locale_info.locale]["price_unit_required"] = _PRICE_UNIT_REQUIRED_BY_LANGUAGE[language]
    logout_success, enterprise_quote_received = _API_SUCCESS_MESSAGES_BY_LANGUAGE[language]
    ERROR_MESSAGES[locale_info.locale]["logout_success"] = logout_success
    ERROR_MESSAGES[locale_info.locale]["enterprise_quote_received"] = enterprise_quote_received
    ERROR_MESSAGES[locale_info.locale]["dataset_source_unavailable"] = (
        _DATASET_SOURCE_UNAVAILABLE_BY_LANGUAGE[language]
    )
    ERROR_MESSAGES[locale_info.locale]["module_unavailable"] = (
        _MODULE_UNAVAILABLE_BY_LANGUAGE[language]
    )

_STATUS_CATEGORY = {
    400: "request_invalid",
    401: "authentication_required",
    402: "subscription_required",
    403: "permission_denied",
    404: "not_found",
    405: "request_invalid",
    409: "conflict",
    413: "request_invalid",
    422: "validation_failed",
    429: "rate_limited",
    500: "internal_error",
    502: "service_unavailable",
    503: "service_unavailable",
    504: "service_unavailable",
}

_TRANSLATION_ROOT = Path(__file__).resolve().parents[3] / "frontend" / "assets" / "i18n"


@lru_cache(maxsize=len(LOCALES))
def _load_translation_catalog(locale: str) -> dict[str, object]:
    path = _TRANSLATION_ROOT / f"{locale}.json"
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return {}


def resolve_api_locale(accept_language: str | None) -> str:
    supported = {locale.casefold(): locale for locale in ERROR_MESSAGES}
    preferences: list[tuple[float, int, str]] = []
    for index, item in enumerate((accept_language or "").split(",")):
        parts = [part.strip() for part in item.split(";")]
        tag = parts[0].replace("_", "-")
        if not tag:
            continue
        quality = 1.0
        for parameter in parts[1:]:
            if parameter.startswith("q="):
                try:
                    quality = float(parameter[2:])
                except ValueError:
                    quality = 0.0
        if quality > 0:
            preferences.append((quality, -index, tag))

    for _, _, tag in sorted(preferences, reverse=True):
        if tag == "*":
            return "fr"
        exact = supported.get(tag.casefold())
        if exact:
            return exact
        language = tag.split("-", 1)[0].casefold()
        base = supported.get(language)
        if base:
            return base
    return "fr"


def http_error_message(
    status_code: int,
    accept_language: str | None,
    detail: object | None = None,
) -> str:
    locale = resolve_api_locale(accept_language)
    detail_text = str(detail or "").strip().casefold()
    if "price analysis requires unit price" in detail_text:
        return ERROR_MESSAGES[locale]["price_unit_required"]
    if "fichier original de ce dataset n'est plus disponible sur le stockage" in detail_text:
        return ERROR_MESSAGES[locale]["dataset_source_unavailable"]
    if "this module is not available for activation" in detail_text:
        return ERROR_MESSAGES[locale]["module_unavailable"]
    if "adresse email doit être vérifiée" in detail_text:
        return ERROR_MESSAGES[locale]["email_verification_required"]
    if "email ou mot de passe incorrect" in detail_text:
        return ERROR_MESSAGES[locale]["invalid_credentials"]
    category = _STATUS_CATEGORY.get(status_code, "request_invalid")
    return ERROR_MESSAGES[locale][category]


def validation_error_message(error_type: str, accept_language: str | None) -> str:
    locale = resolve_api_locale(accept_language)
    category = "required_field" if error_type == "missing" else "invalid_value"
    return ERROR_MESSAGES[locale][category]


def validation_summary(accept_language: str | None) -> str:
    locale = resolve_api_locale(accept_language)
    return ERROR_MESSAGES[locale]["validation_failed"]


def localized_api_message(accept_language: str | None, key: str) -> str:
    locale = resolve_api_locale(accept_language)
    return ERROR_MESSAGES[locale][key]


def catalog_message(
    accept_language: str | None,
    section: str,
    key: str,
    fallback: str,
) -> str:
    """Resolve a user-facing response message from the shipped locale catalog."""
    locale = resolve_api_locale(accept_language)
    value = _load_translation_catalog(locale).get(section)
    if isinstance(value, dict):
        message = value.get(key)
        if isinstance(message, str) and message.strip():
            return message
    return fallback